### PR TITLE
Update MAGIC API and docs

### PR DESCRIPTION
**Pull request by scottgigante**
The MAGIC docs and API are a little out of date.

### CODE REVIEW

**Comment by flying-sheep** [comment]
Thank you! As it stands, this destroys backwards compatibility. But fear not:

1. Add [`legacy-api-wrap`](https://pypi.org/project/legacy-api-wrap/) to requirements.txt and docs/requirements.txt
2. Use it to change the API to 1-2 positional parameters (i.e. either `def magic(adata: ..., *, name_list: ... = None, ...)` or with the `*` one parameter to the right)
3. While you’re at it, change `name_list`’s type to `Union[Literal['all_genes', 'pca_only'], Sequence[str], None]`. You can do `from .._compat import Literal` or so (maybe a dot less or more)

**Comment by scottgigante** [comment]
Wow, I learned something new! Thanks!

**Comment by flying-sheep** [comment]
Looks good, just one style thing remaining! You can just do `python -m black path/to/file.py` instead of doing things manually

**Comment by flying-sheep** [comment]
Thank you!

**Comment by scottgigante** [comment]
Thanks @flying-sheep ! I've also started using `black` in my own code now. You might be interested in this - I've added a git hook to automatically format any committed `.py` files with `black`.

https://github.com/KrishnaswamyLab/scprep/blob/master/autoblack.sh

**Comment by flying-sheep** [comment]
Thanks, I use it [this way](https://black.readthedocs.io/en/stable/version_control_integration.html).

**Comment by scottgigante** [comment]
That's much nicer, thanks!

**Pull request merged**
