### PR TITLE
update tutorials

### PR DESCRIPTION
**Pull request by flying-sheep**

### CODE REVIEW

**Review by Zethson — APPROVED** [review]

**Comment by Zethson** [comment]
@grst is also a good person to ping for tutorials. In general, we'll also want to link to more scverse tutorials eventually

**Comment by grst** [comment]
Relevant issues about `scverse.org/learn`: 

 * https://github.com/scverse/scverse-tutorials/issues/58
 * https://github.com/scverse/scverse-tutorials/issues/60

Tutorial registry is [here](https://github.com/scverse/scverse-tutorials/tree/main/tutorial-registry) and works in principle, but needs to be filled with content as described in https://github.com/scverse/scverse-tutorials/issues/58

**Comment by flying-sheep** [comment]
OK, I just wanted to get things in. Is there an issue about cleaning everything up? (make the scanpy-tutorials.rtfd.io redirect, make the tutorial registry visible, …?)

**Comment by grst** [comment]
No, there's currently no meta issue (feel free to create). 
However the list of all issues in scverse-tutorials is still manageable: https://github.com/scverse/scverse-tutorials/issues

**Comment by flying-sheep** [comment]
OK, then no need to add that.

**Pull request merged**
