### PR TITLE
Bump umap to 0.5.5, remove most compat code

### LINKED ISSUE #2012: Increase pinned version of UMAP
Recent discussions on speed demonstrated that UMAP >= 0.5 implementations increase the speed.
Should we increase the minimal version? https://github.com/theislab/scanpy/blob/master/pyproject.toml#L63

CC @le-ander

### PR DESCRIPTION
**Pull request by flying-sheep**
- [x] Closes #2012
- [x] Tests included or not required because:

- [ ] Release notes not necessary because:

TODO:

- [ ] Figure out and fix this: https://github.com/scverse/scanpy/blob/4fb3dc7d11f1b067f0aea1008cd3e7fbc3e5d54c/scanpy/metrics/_gearys_c.py#L128-L131 (related to https://github.com/numba/numba/issues/6976?)
- [x] Maybe remove these: https://github.com/scverse/scanpy/blob/4fb3dc7d11f1b067f0aea1008cd3e7fbc3e5d54c/scanpy/tools/_umap.py#L167-L171 https://github.com/scverse/scanpy/blob/4fb3dc7d11f1b067f0aea1008cd3e7fbc3e5d54c/scanpy/neighbors/_connectivity.py#L120-L123
- [x] release notes

### CODE REVIEW

**Comment by ivirshup** [comment]
Looking at the code cover report, there is some more dead code:

https://app.codecov.io/gh/scverse/scanpy/pull/2870?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=scverse#diff-c2NhbnB5L3Rvb2xzL19pbmdlc3QucHk=

**Comment by flying-sheep** [comment]
all done!

**Comment by ivirshup** [comment]
> Figure out and fix this:

I think the `tbb` thing can be a `TODO` for this. Things work as is, and I don't know off the top of my head if we can reliably fix this.

**Comment by flying-sheep** [comment]
OK! Tests should pass now too

**Comment by ivirshup** [comment]
I'd like to bump the version requirement down a bit, since it seems like it's not that uncommon to pin `map-learn` lower than 0.5.5: https://github.com/search?q=%2F%5B%22%27%5D%3Fumap-learn%5B%22%27%5D%3F%5B%3D%3E%3C%5D%2B%2F&type=code

The cellxgene one is worrying

**Review by ivirshup — APPROVED** [review]

**Pull request merged**
