### PR TITLE
Add ylabel option to violin

### PR DESCRIPTION
**Pull request by michalk8**
This PR adds option to add y-label to violin plot, see below:
```python
sc.pl.violin(adata, ['initial_size', 'initial_size_spliced'], groupby='clusters',
             ylabel=['foo', 'bar'])
```
violin

`ylabel` is by default `None`, preserving the original behaviour.
Also fixes an issue when there are duplicate keys and `groupby != None`, such as:
```python
sc.pl.violin(adata, ['initial_size', 'initial_size_spliced', 'initial_size'],
             groupby='clusters')
```
Previously, it created a figure with 3 axes, now are only 2 (order of keys is being preserved).

### CODE REVIEW

**Comment by Marius1311** [comment]
Hi all, is there any progress on this? @michalk8 and myself rely on this for a package we are currently developing.

**Comment by fidelram** [comment]
@Marius1311 Thanks a lot for adding this. I reviewed the code and do not have any objections to merge it. Would be possible to add or modify one of the plotting tests where this new parameter is used?

**Comment by Marius1311** [comment]
Thanks @fidelram ! It was actually @michalk8 who wrote this :)

**Comment by Marius1311** [comment]
@michalk8 , would be great to add a test for this.

**Comment by fidelram** [comment]
> Thanks @fidelram ! It was actually @michalk8 who wrote this :)

Sorry for the confusion.

**Review by fidelram — APPROVED** [review]
Would be great to modify one of the test to add this parameter.

**Comment by michalk8** [comment]
@fidelram sorry it took so long... I've added the param to one of the tests.

**Comment by Marius1311** [comment]
thanks!

**Pull request merged**
