### PR TITLE
Increase ubuntu version & python version for azure CI

### LINKED ISSUE #2446: Azure removes support for Ubuntu 18
https://github.com/scverse/scanpy/blob/master/.azure-pipelines.yml#L14

https://learn.microsoft.com/en-us/answers/questions/1181262/what-happens-to-azure-vms-with-ubuntu-18-04-lts-af

and our CI already cries about it. Let's up this to a more recent version, maybe even 22.04?

While we're at it, I'd also remove 3.7 from the CI because it'll lose support very soon. We could add one of the more recent Python versions instead.

### PR DESCRIPTION
**Pull request by Zethson**
Fixes #2446 

Python 3.7 is EOL in 3 months https://endoflife.date/python and Pandas hasn't supported it for a loooong time already.

### CODE REVIEW

**Comment by ivirshup** [comment]
Happy to bump the ubuntu version. Would also like this to happen on the backport branch.

I want to keep testing against the lowest python version we support. In theory we could jump to 3.9 as the minimum version. But I think numpy is still at 3.8, so that's reasonable too. Would you want to make this change here, or split to a separate PR?

**Review by ivirshup — COMMENTED** [review]
Happy to bump the ubuntu version. Would also like this to happen on the backport branch.

I want to keep testing against the lowest python version we support. [In theory we could jump to 3.9 as the minimum version](https://scientific-python.org/specs/spec-0000/#description). But I think numpy is still at 3.8, so that's reasonable too. Would you want to make this change here, or split to a separate PR?

**Comment by Zethson** [comment]
I personally think that we have enough users that are still on 3.8 so I'd keep it at 3.8?

Are you now trying to say that the lowest version that we're supporting is 3.7 or 3.9?

If we agree on 3.8 being the minimum I'd just keep the PR as it is and merge.

**Comment by ivirshup** [comment]
I'm saying either:

* Don't change the CI python version
* Or: Change the minimum python version for the project to 3.8 as well

https://github.com/scverse/scanpy/blob/0692ef9ea30335b95f7e7f9aab7be856469d9f35/pyproject.toml#L13

**Comment by Zethson** [comment]
Got it, thanks. I'll increase the minimum Python version to 3.8. I'll also check which compatibility code we can remove later. I'll ask for another review then.

**Comment by flying-sheep** [comment]
@meeseeksdev backport to 1.9.x

**Pull request merged**
