### PR TITLE
n_trees is annoy_n_trees in bbknn 1.5.x

### PR DESCRIPTION
**Pull request by pinin4fjords**
Latest BBKNN versions (>=1.5.x) [uses annoy_n_trees in place of n_trees](https://github.com/Teichlab/bbknn/commit/288e05990c74467601c263a23538779991fb7635), just applying that fix here.

### CODE REVIEW

**Comment by ktpolanski** [comment]
I've already opened a [more comprehensive PR](https://github.com/theislab/scanpy/pull/1868) for this five days ago, but haven't heard back on it.

**Comment by pinin4fjords** [comment]
Ahh, apologies @ktpolanski , closing now.

**Comment by ktpolanski** [comment]
All good, thanks for doing this :)

**Comment by genecell** [comment]
Hi, 

I also met this problem. I am using Scanpy 1.7.2, and could you please suggest which version of BBKNN I should use if I don't want to update Scanpy to 1.8.0.

Thanks,
Min

**Comment by ktpolanski** [comment]
Two options:
- bbknn < 1.5.0
- use `bbknn.bbknn()` instead of the scanpy wrapper

**Comment by genecell** [comment]
> Two options:
> 
> * bbknn < 1.5.0
> * use `bbknn.bbknn()` instead of the scanpy wrapper

Thank you for your rapid reply, bbknn 1.4 works for me (scanpy 1.7.2). The second option is good.
Thanks!

**Pull request closed without merging**
