### PR TITLE
Scoring functions

### PR DESCRIPTION
**Pull request by dawe**
I believe everything is in place. We should have now a generic `add_score` which scores cells according to expression of gene lists. That is wrapped twice in `cell_cycle_score`.

### CODE REVIEW

**Comment by falexwolf** [comment]
Hi Davide!

Thank you very much for this! Sorry that I tend to be late these days, have two 6 week old baby twins to take care of...

I'm happy to merge this and I'll add you to the author list! I hope it is ok if I rename the module and the top-level function to `score_gene_lists`  and the second top-level function to `score_cell_cylce_genes`? Simply `score` is a bit generic... there might be many other scores in the future and then people will get confused. It's also good if both start with `score` so that auto-lookup gives you directly these suggestions? 

Also, do you have a notebook with an example? It would be cool to see this at work. You could push this to a new subdirectory in `scanpy_usage`: https://github.com/theislab/scanpy_usage. I just sent you a collaborator invitation. From the example, we can then mayb design a test that goes a bit more into detail. Would be cool to benchmark with Seurat, for example.

Also, one could think about providing a default list of genes, right? In particular for the cell cycle, it would be nice to directly call the function with default parameters - one can then still add user-specified lists. Do you want to provide such a list? I also sent you collaborator invitation for scanpy - maybe only temporarily if we get too many people at some point - so that you can quickly add this, if you like.

Cheers,
  Alex

**Comment by falexwolf** [comment]
Finally: it would be great to add a bit more explanation on how the comparison with the random gene set works exactly. I can also do this...

**Comment by falexwolf** [comment]
I've now also added this to the [documentation](https://scanpy.readthedocs.io/en/latest/api/index.html#tools-tl) so that we see how "it looks".

Do you think the naming convention is good like that? Or shall we rather make it `score_gene_sets` and `score_genes_cell_cycle` [more symmetry and more rigour in naming?]. Now we can easily change this without having to worry about backwards compat... ;)

**Comment by dawe** [comment]
@falexwolf I'm glad you merged. A couple of things

- ok for the name change. I see you have a different naming and syntax style, I'll try to stick to that (e.g. no space around operators)
- I do not have any notebook ready, I'll prepare one
- As for the gene list, I used the Regev lab one, I'm adding that into the notebook
- I will try to explain how the comparison works. I actually had to figure it out myself, as reverse engineering `R` code is far beyond human capabilities :-)
- you don't have to apologize for being late. I'm father of two and I haven't worked after 21:00 since my first was born 7 years ago

**Comment by falexwolf** [comment]
@dawe 
- the coding style is the [official python coding style](https://www.python.org/dev/peps/pep-0008/), we should all stick to that. in particular: [white spaces](https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements) around operators but **not** around optional keyword arguments
- thank you for a notebook!
- gene list: why not add it as an attribute of your module? or make a class `GeneLists` with a few gene lists in your model? of course, these will not be comprehensive, but might provide a good starting point
- in a few instances, I had to go through the reverse R engineering myself - in particular, if it comes to benchmarking code to floating point precision, it's really a hassle to dig out all the hidden different conventions... but I think it really pays off in the sense that it provides a lot more confidence in code and methods if several tools provide the same result on basic things - even across languages

**Comment by dawe** [comment]
@falexwolf 

Too bad I have never read the official coding style, I guess that happens when you are a self-taught programmer :-) Not to mention I still have difficulties with git. You have been warned :-D

**Comment by dawe** [comment]
@falexwolf I've added a silly notebook in the scanpy_usage repo showing cell cycle regression, pretty much following most important bits of [Seurat's vignette](http://satijalab.org/seurat/cell_cycle_vignette.html#assign-cell-cycle-scores). Note that this will work only after the scoring function code will be fixed. As mentioned in #82 , when my functions were merged and names changed, not all calls were renamed.

**Comment by falexwolf** [comment]
Oh, thank you! I'll go through this tonight!

I will polish it, check it and once again rethink the naming conventions, as mentioned just a few minutes ago.

**Pull request merged**
