### PR TITLE
Fix qcmetrics when no top proportions are requested

### PR DESCRIPTION
**Pull request by ivirshup**
Fix for #421, and a bounds check on `percentage_top` argument.

### CODE REVIEW

**Comment by fidelram** [comment]
@ivirshup Do you mind adding as part of the PR an extended description of the function? I don't think that everyone is familiar with `calculateQCMetrics` and thus, the output of this function is unclear.

**Comment by ivirshup** [comment]
Are there any particular areas you'd like to see expanded? Otherwise, maybe an example would help? I'm thinking something like:

```python
Example
-------

>>> adata = sc.datasets.pbmc3k()
>>> sc.pp.calculate_qc_metrics(adata, inplace=True)
>>> sns.jointplot(adata.obs, "log1p_total_counts", "log1p_n_genes_by_counts", kind="hex")
```

or something longer (though I think this is in one of the tutorials):

```python
Example
-------

>>> adata = sc.datasets.pbmc3k()
>>> adata.var["mito"] = adata.var_names.str.startswith("MT-")
>>> sc.pp.calculate_qc_metrics(adata, qc_vars=["mito"], inplace=True)
>>> sns.jointplot(adata.obs, "log1p_total_counts", "pct_counts_mito", kind="hex")
```

**Comment by fidelram** [comment]
A summary of the output from this page would be too difficult or maybe add the link?https://www.rdocumentation.org/packages/scater/versions/1.0.4/topics/calculateQCMetrics (btw, is this the right function?)

Adding an example is a good idea. Could be the shorter version.

**Comment by ivirshup** [comment]
It's the right function, but those docs are out of date (current version is `v1.10.1`). There's an up to date PDF on their bioconductor page, but I don't think I can link to the function from there.

How about this: <details>
<summary>Updated docstring</summary>

```python
def calculate_qc_metrics(adata, expr_type="counts", var_type="genes", qc_vars=(),
                         percent_top=(50, 100, 200, 500), inplace=False):
    """
    Calculate quality control metrics.

    Calculates a number of qc metrics for an AnnData object, see section 
    Returns for specifics. Largely based on `calculateQCMetrics` from scater
    [McCarthy17]_. Currently is most efficient on a sparse CSR or dense matrix.

    Parameters
    ----------
    adata : :class:`~anndata.AnnData`
        Annotated data matrix.
    expr_type : `str`, optional (default: `"counts"`)
        Name of kind of values in X.
    var_type : `str`, optional (default: `"genes"`)
        The kind of thing the variables are.
    qc_vars : `Container`, optional (default: `()`)
        Keys for boolean columns of `.var` which identify variables you could 
        want to control for (e.g. "ERCC" or "mito").
    percent_top : `Container[int]`, optional (default: `(50, 100, 200, 500)`)
        Which proportions of top genes to cover. If empty or `None` don't
        calculate.
    inplace : bool, optional (default: `False`)
        Whether to place calculated metrics in `.obs` and `.var`

    Returns
    -------
    Union[NoneType, Tuple[pd.DataFrame, pd.DataFrame]]
        Depending on `inplace` returns calculated metrics (`pd.DataFrame`) or
        updates `adata`'s `obs` and `var`.

        Observation level metrics include:

        * `total_{var_type}_by_{expr_type}`
            E.g. "total_genes_by_counts". Number of genes with positive counts 
            in a cell.
        * `total_{expr_type}`
            E.g. "total_counts". Total number of counts for a cell.
        * `pct_{expr_type}_in_top_{n}_{var_type}` - for `n` in `percent_top`
            E.g. "pct_counts_in_top_50_genes". Cumulative percentage of counts 
            for 50 most expressed genes in a cell.
        * `total_{expr_type}_{qc_var}` - for `qc_var` in `qc_vars`
            E.g. "total_counts_mito". Total number of counts for variabes in 
            `qc_vars`.
        * `pct_{expr_type}_{qc_var}` - for `qc_var` in `qc_vars`
            E.g. "pct_counts_mito". Proportion of total counts for a cell which 
            are mitochondrial.

        Variable level metrics include:

        * `total_{expr_type}`
            E.g. "total_counts". Sum of counts for a gene.
        * `mean_{expr_type}`
            E.g. "mean counts". Mean expression over all cells.
        * `n_cells_by_{expr_type}`
            E.g. "n_cells_by_counts". Number of cells this expression is 
            measured in.
        * `pct_dropout_by_{expr_type}`
            E.g. "pct_dropout_by_counts". Percentage of cells this feature does 
            not appear in.
    

    Example
    -------
    Calculate qc metrics for visualization.

    >>> adata = sc.datasets.pbmc3k()
    >>> sc.pp.calculate_qc_metrics(adata, inplace=True)
    >>> sns.jointplot(adata.obs, "log1p_total_counts", "log1p_n_genes_by_counts", kind="hex")
    """
```

</details>

**Comment by fidelram** [comment]
I think that the updated docstring is much better.

**Comment by falexwolf** [comment]
Thank you, this is great! :smile: Sorry for the late response, it just came in after I went through the issues last weekend...

**Pull request merged**
