### PR TITLE
Add PHATE integration

### PR DESCRIPTION
**Pull request by scottgigante**
Hi! I've added two possible APIs for PHATE: I imagine you'll only want to include one of them. 

The first, `sc.tl.PHATE`, is an object-oriented interface that matches `phate.PHATE`, which looks like an `sklearn` estimator class. The second is a functional interface which is equivalent to running `phate.PHATE().fit_transform(data)`. The second is more simple, but less powerful as any changes in parameters will require the entire operator to be recomputed, where the object-oriented interface allows partial recomputation.

Please let me know which you prefer (or if you would like to include both!) If we only include the functional version I would probably rename it to `phate` rather than `run_phate`.

### CODE REVIEW

**Comment by falexwolf** [comment]
Hi Scott!

Sorry that I didn't see this before writing the following email this moring:

> Sorry about forgetting to mention this in the first email below (just thought I'd send you the link to the most recent wrapper). The tSNE tool is a wrapper, too, and also has an example for a visualization function
> https://github.com/theislab/scanpy/blob/master/scanpy/tools/tsne.py
> https://github.com/theislab/scanpy/blob/master/scanpy/plotting/tools/__init__.py#L426-L518
> You'll find the corresponding pair in the docs. If your wrapper parallelizes this, this will make it very easy for Scanpy users to use out PHATE.

Scanpy's toplevel API does - on purpose - not feature objects, but convenience functions. If people want to do more complicated stuff, they should directly use the PHATE package, in this case.

So, it would be nice if you'd only provide the convenience function - which is already very similar to what I pasted about tSNE.

Also, please remove phate from the requirements... and raise a corresponding ImportError in your convenience function. Scanpy has quite some optional dependencies and Phate will be one of them.

Thank you!

**Comment by falexwolf** [comment]
PS: You don't need a test for this... it would require installing phate on travis and this would take time... Also, the interface is trivial. You should simply link to your package within the docs to redirect people for bugs and more info.

**Comment by scottgigante** [comment]
@falexwolf thanks very much for the extra information! I've copied the t-SNE API so it should fit much more cleanly into the scanpy interface. Let me know if there's anything else you need me to change. Thanks again!

**Comment by falexwolf** [comment]
Merged. :wink:

**Comment by falexwolf** [comment]
Nice! You also provided an example in the doc strings...!

**Pull request merged**
