### PR TITLE
Plotting overhaul

### PR DESCRIPTION
**Pull request by flying-sheep**

### CODE REVIEW

**Comment by ivirshup** [comment]
@flying-sheep, for this, were you thinking to update `adata.obs_vector` to throw errors with ambiguities , `sc.get.obsdf`, or both?

I'm wondering if there should be some period of deprecation warnings for that. I also think it's fair to consider it a bug.

**Comment by fidelram** [comment]
I am doing some changes to `sc.pl.dotplot` see #1127 I hope that we are not overlapping.

**Comment by fidelram** [comment]
I will try to incorporate the changes that are not related to scatterplots into #1127

**Comment by flying-sheep** [comment]
Hey, I'm currently trying to finish up my thesis, sorry for the lack of communication.

As this currently mostly adds code, go ahead and change what you want, I'll rebase this once theislab/anndata#342 is through.

**Comment by Zethson** [comment]
@flying-sheep do you want to close this in favor of your future much more powerful plotting revamp?

**Comment by flying-sheep** [comment]
oof sad that this didn’t make it, seems like there were some nice bits in there.

**Pull request closed without merging**
