### PR TITLE
Fixes highly_variable_genes failing with `batch_key` and `inplace=False`

### PR DESCRIPTION
**Pull request by atarashansky**
Fixes issue #1033

### CODE REVIEW

**Comment by ivirshup** [comment]
Thanks for the PR! Could you add a test to make sure it works?

**Comment by atarashansky** [comment]
Do you mean to add a test for TravisCI (sorry, I'm new to this)?

**Comment by ivirshup** [comment]
Yeah, there are a bunch of methods which run under CI in under the `scanpy/tests` directory. These should go in the `scanpy/tests/test_highly_variable_genes.py` file. Basically just make sure the results are what they should be. In this case, the returned object should have the same values as those added to the anndata when `inplace=True`.

We use [pytest](https://docs.pytest.org/en/latest/) to run the tests. You can run the tests locally by calling `pytest` at the root of the repo, and you can specify which tests to run with `pytest -k pattern` where `pattern` matches against the test names.

Feel free to ask if you come across any problems!

**Comment by ivirshup** [comment]
@atarashansky, the performance is looking very very good:

```python
import scanpy as sc
import numpy as np
from sklearn.datasets import fetch_20newsgroups_vectorized

X = fetch_20newsgroups_vectorized("all").data
# 18846 x 130107 csr_matrix

a = sc.AnnData(X, dtype=np.float64)
%time implicit = sc.pp.pca(a, pca_sparse=True, dtype=np.float64, copy=True)
# CPU times: user 34.8 s, sys: 5.52 s, total: 40.3 s
# Wall time: 2.93 s
# Peak memory (including dataset) is about 770 MB
%time explicit = sc.pp.pca(a, pca_sparse=False, dtype=np.float64, copy=True)
# CPU times: user 55min 37s, sys: 1min 50s, total: 57min 28s
# Wall time: 7min 43s
# Peak memory is about 36 GB

assert np.allclose(implicit.obsm["X_pca"], explicit.obsm["X_pca"])
assert np.allclose(implicit.varm["PCs"], explicit.varm["PCs"])
```

But the variance and explained variance ratio are still off. Why not calculate them the same way sklearn does?

Also, any thoughts on making a PR there?

**Comment by ivirshup** [comment]
Closing as the underlying issue seems to have been fixed.

**Pull request closed without merging**
