### PR TITLE
Fix docstrings for `scanpy.tl.rank_genes_groups`

### LINKED ISSUE #1416: Docs for `scanpy.tl.rank_genes_groups` are displayed incorrectly
The docs for `scanpy.tl.rank_genes_groups` are displayed incorrectly [here](https://scanpy.readthedocs.io/en/stable/api/scanpy.tl.rank_genes_groups.html#scanpy.tl.rank_genes_groups). The problem is the empty line [here](https://github.com/theislab/scanpy/blob/f704f724529def21769ee6407f9b47b5c161564c/scanpy/tools/_rank_genes_groups.py#L518).

### PR DESCRIPTION
**Pull request by WeilerP**
## Changes

* Removes empty line causing the example terminal commands to be displayed incorrectly.
* Prepends `>>>` to comment.

## Related issues

Closes #1416.

### CODE REVIEW

**Comment by fidelram** [comment]
Tests are failing and I suspect that this is caused by an update on seaborn or matplotlib...

**Comment by WeilerP** [comment]
> Tests are failing and I suspect that this is caused by an update on seaborn or matplotlib...

Yes, should be as the introduced changes are not linked to the failing tests. I also checked and both `seaborn` and `matplotlib` have been updated in the last few days. See [here](https://pypi.org/project/seaborn/#history) and [here](https://pypi.org/project/matplotlib/#history).

**Comment by fidelram** [comment]
Thanks. I just confirmed that the newer versions for both packages were used in the tests. I am checking now what is the difference.

**Comment by WeilerP** [comment]
When running the tests locally with Python 3.7, `seaborn` seems to be the problem, as the tests pass for `matplotlib==3.3.2` and `seaborn==0.10.1`.

**Comment by fidelram** [comment]
Indeed, seaborn is the problem. I am getting the plots horizontal when they should be  vertical:

image

**Comment by WeilerP** [comment]
The problem seems to be [here](https://github.com/theislab/scanpy/blob/f704f724529def21769ee6407f9b47b5c161564c/scanpy/plotting/_anndata.py#L745) and [here](https://github.com/theislab/scanpy/blob/f704f724529def21769ee6407f9b47b5c161564c/scanpy/plotting/_anndata.py#L747) as `seaborn` throws the warning

```bash
UserWarning: Vertical orientation ignored with only `x` specified.
```

in the stack trace of the failed tests. I'll open a separate issue as it is unrelated to this PR.

**Comment by fidelram** [comment]
Let's merge once #1420 is solved.

**Comment by fidelram** [comment]
@WeilerP Can you merge with master to trigger CI?

**Comment by WeilerP** [comment]
@fidelram, I merged with master and all tests pass. Should be ready to merge.

**Pull request merged**
