### PR TITLE
Don't allow h5py 2.10.0

### PR DESCRIPTION
**Pull request by ivirshup**
Trying to fix the build

### CODE REVIEW

**Comment by ivirshup** [comment]
@gokceneraslan 

This fixes the builds for now. I'm guessing there's some bug added on their end, but haven't confirmed this yet.

Some more notes:

A reason I think a bug could be on our end is that current master of anndata reads that dataset just fine, so maybe the previous code relied on unintended behavior.

**Comment by gokceneraslan** [comment]
Cool! Thanks a lot.

**Comment by flying-sheep** [comment]
Where’s the bug on their end? You did file one, right?

**Comment by flying-sheep** [comment]
I can’t reproduce this locally and would like to get the dependencies unlocked. Where’s the bug report at h5py?

**Comment by ivirshup** [comment]
I'm pretty sure I fixed this around here: https://github.com/theislab/anndata/commit/38e687c32b87cc9cadde2fbd977b36bfb08f00f3, but I opened the issue here: https://github.com/h5py/h5py/issues/1307

**Comment by flying-sheep** [comment]
Thank you!

**Pull request merged**
