### PR TITLE
Fix ingest for the new umap

### PR DESCRIPTION
**Pull request by Koncopd**
This should fix the problems with the new release candidate of umap.
https://github.com/theislab/scanpy/issues/1036

### CODE REVIEW

**Comment by flying-sheep** [comment]
Nice! But may I ask why you’re still importing everything from umap instead of from pynndescent?

I’d assume if we’d do that we’d be more robust to further umap updates, no?

**Comment by Koncopd** [comment]
Hm, it is still required to follow the internals of umap to reconstruct UMAP object from anndata info. Also this adds dependency on pynndescent.

**Comment by flying-sheep** [comment]
OK. @lmcinnes, is there a better way to construct fitted umap objects from primitives?

**Comment by lmcinnes** [comment]
This looks pretty reasonable for now -- the newer version tried to clean up a lot of t5hese sorts of issues, but backwards compatibility is now an issue I guess.

**Comment by flying-sheep** [comment]
Great, if the new way is going to continue to work, everything’s fine!

**Pull request merged**
