### PR TITLE
WIP Scran Normalization

### PR DESCRIPTION
**Pull request by NataliaVoro**
Implements Normalization like scran's computeSumFactors method.

### CODE REVIEW

**Comment by LuckyMD** [comment]
looking forward to this being implemented! Will greatly increase the speed of most of my analysis workflows 😃

**Comment by jipeifeng** [comment]
looking forward to it !

**Comment by cdedonno** [comment]
Hey guys @LuckyMD, @Koncopd, @falexwolf, @flying-sheep. I think this feature would be very useful to have in Scanpy, but this PR has been sort of forgotten. 

I would be up to take care of this, but it would be my first contribution and I'd like some advice on how to move forward on this. I take it the main issue with the PR is the missing test for the scran normalization, is that correct?

**Comment by LuckyMD** [comment]
A student of @mbuttner started this, and yes, I believe it's only missing tests. I would probably make a small test case and record the results of the `R` version on there, and use it as a test for this. You can check out the `testing/` directory for tests. 

To start, just fetch this branch and you should be able to commit to it directly as a member of theislab github.

**Comment by cdedonno** [comment]
Unfortunately the PR was not just missing some tests. There are quite a lot of missing parts and the code is not correct. This will take much more effort than expected. I will try working on it on my own branch and close this PR.

**Comment by mbuttner** [comment]
I'm sorry to hear this and hope that you can still use it as a basis for your own implementation. Thank you so much for your effort!

**Comment by cdedonno** [comment]
Yes, it's definitely better than starting from scratch!

**Pull request closed without merging**
