### PR TITLE
Inherit layer argument in _highly_variable_genes_single_batch when using sc.pp.highly_variable_genes

### PR DESCRIPTION
**Pull request by Ngort**
Quite a simple addition meant to fix a bug when one works with specific layers.

### CODE REVIEW

**Comment by Zethson** [comment]
Could you please run black?

```
black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted scanpy/preprocessing/_highly_variable_genes.py

All done! ✨ 🍰 ✨
1 file reformatted, 152 files left unchanged.
```

**Comment by ivirshup** [comment]
That definitely looks wrong on our end....

Can you add a test for this?

**Comment by Zethson** [comment]
@Ngort we'd be happy to get this PR in if you address the comments above.

**Comment by DriesSchaumont** [comment]
> @Ngort we'd be happy to get this PR in if you address the comments above.

@Zethson I think this was fixed in #2302

**Comment by Zethson** [comment]
@DriesSchaumont Thanks!

**Comment by flying-sheep** [comment]
We should make sure to get fixes like this in by fixing style issues with PRs ourselves.

**Pull request closed without merging**
