### PR TITLE
compare_abs argument in filter_rank_genes_groups

### PR DESCRIPTION
**Pull request by Koncopd**
Argument to compare absolute values of log fold change with `min_fold_change`.
https://github.com/theislab/scanpy/issues/1325
I think `compare_abs` is a better name than `rankby_abs` for this.

### CODE REVIEW

**Comment by fidelram** [comment]
I take note that we should allow all this parameters to be passed from the graphical functions to `sc.get.rank_genes_groups_df` in #1529

**Comment by ivirshup** [comment]
@Koncopd @fidelram I've added a discussion of this function to the agenda for the next call. I think it would be good to figure out our plan before making changes.

**Comment by Koncopd** [comment]
@ivirshup @fidelram So what do we do with this?

**Comment by ivirshup** [comment]
I believe @fidelram isn't super available for scanpy stuff until next month. I figured we could talk about this then.

**Pull request merged**
