### PR TITLE
Fix use_raw=None in scanpy.tl.score_genes

### PR DESCRIPTION
**Pull request by michalk8**
This PR fixes the case when `use_raw=None` in `scanpy.tl.score_genes`. It causes to first fetch `var_names` from `adata.var_names`, but later a subset on `adata.raw` can happen, which can have different gene names.
Also fixes the type of `use_raw` and  adds a `ValueError` if `gene_pool` is empty (otherwise, crashes with non-informative error message).

related issue: https://github.com/theislab/cellrank/issues/746

### CODE REVIEW

**Review by ivirshup — COMMENTED** [review]
LGTM, just needs a release note

**Comment by ivirshup** [comment]
Could the note be a little more descriptive? Without a specific issue linked to this it's hard to tell what incorrect behavior was changed.

**Comment by ivirshup** [comment]
Great, thanks!

We do have the CI checks as required for merging, unfortunately.

Question for you about the `pre-commit` CI. Do you know what's going on here with the extra service? Do we no longer need the github actions pre-commit check? Can also figure this out on Friday.

**Comment by ivirshup** [comment]
Heads up, I'm going to make an empty commit to re-trigger the CI.

**Comment by michalk8** [comment]
> We do have the CI checks as required for merging, unfortunately.

Ok, didn't wanted to waste the resources and thought you can just merge manually even if checks don't pass.

> Question for you about the pre-commit CI. Do you know what's going on here with the extra service? Do we no longer need the github actions pre-commit check? Can also figure this out on Friday.

Yes, afaik this was enabled a few weeks back for the whole organization.

**Pull request merged**
