### PR TITLE
updated Scanpy to support Weighted sampled data to perform clustering…

### PR DESCRIPTION
**Pull request by Khalid-Usman**
I have added source code for weighted sampled data. I have already preprocessed data and found the top few PC's and then input to `scanpy `to find `louvain `communities , `marker genes` and later variety of plots like `dotPlot`, `violinPlot `and `heatmap`. I have updated `scanpy `for `weighted `sampled data where each row has its weight, but this support for clustering and plotting. We can further update` sparse PCA` as well to support weighted data points.

### CODE REVIEW

**Comment by flying-sheep** [comment]
seems like you did something wrong. the commit you added (74540cc133ca9cfe0744ca9d3b250454a76a9c4d) reverts a lot of changes we made since.

i assume you just copied all your code over the current master branch, and not the version of the master branch as it was when you made the changes.

you need to find the version of scanpy that you downloaded before you made your changes and modify that one to have just the changes you want to commit. otherwise we have no idea what your actual changes are.

**Comment by Khalid-Usman** [comment]
Hi,

I have modified version 1.4, but i think git only allow latest version to
fork. Is there any other simple way, so that i can share my code for Scanpy
version 1.4.

Thanks,
Khalid

**Comment by flying-sheep** [comment]
yes!

1. make sure you have all of your modified copy somewhere outside of the cloned directory! we’re going to destroy all changes inside of that directory!
2. Destroy all changes and go back to 1.4: `git reset --hard 1.4` (if it’s really 1.4 and not e.g. 1.4.1)
3. Make a new branch based on 1.4: `git checkout -b weighted-clustering`
4. Copy your changes over again.
5. Check if all is right: `git diff` should only tell you about your modified files, not other junk.
6. Add all files you changed individually (not `git add .` or `git add -A`, but `git add scanpy/file1.py scanpy/file2.py ...`)
7. `git diff` should now say that there’s a few staged files (your modifications), and no other added or modified files.
8. Commit your changes `git commit -m 'your commit message'` and push them `git push`

Now you can make a new PR with just your changes in it: https://github.com/theislab/scanpy/compare/master...Khalid-Usman:weighted-clustering

Make sure that you only see your changes on the lower part of that page before hitting the “Create Pull Request” button

**Comment by Khalid-Usman** [comment]
Is it fine or need to do anything else before make a pull request ?

Thanks

**Comment by flying-sheep** [comment]
You can just open a new one, I’ll close this one then :slightly_smiling_face:

**Comment by Khalid-Usman** [comment]
Ok , thanks for letting me know. Please check the pull request. I have
verified my code by keeping weights 1 and it has same values when
observations has no weights or all weights equal to 1.

I also suggest to update PCA for weighted sampled data.

Thanks,
Khalid Usman

**Comment by Khalid-Usman** [comment]
Hi Phillip,

I have removed issue from the pull request by the testing tool, now the
tools showed me duplications, which are mostly from other code and 1-2 from
my code. Please have a look into it. It's my first pull request and its
taking too much time :(

Thanks
Khalid

**Comment by Khalid-Usman** [comment]
Thanks alot Philip for your help, I just learned testing :)

Hopefully this version will be accepted, as I tested now on my laptop and
push when it passed tests for all 5 plots.

Thanks,
Khalid

**Pull request closed without merging**
