### PR TITLE
Update the News section

### PR DESCRIPTION
**Pull request by falexwolf**
@ivirshup, as discussed!

### CODE REVIEW

**Comment by LuckyMD** [comment]
This is really cool! How expansive should this be? Scanpy core + scvelo? Or also other scanpy-based things like single-cell-tutorial, scGen, scvi-tools or diffxpy?

In our data integration benchmarking we find that 3 of the top 4 tools are in the scanpy ecosystem now: scanorama, scGen, and scANVI.

**Comment by falexwolf** [comment]
Happy to have this be quite extensive!

Not happy with the font styling. We should make this a separate page and just show the top of the thread on the landing page.

**Comment by falexwolf** [comment]
@LuckyMD, feel free to add news!

**Comment by LuckyMD** [comment]
Will do once there are things that are big enough... you set the bar quite high with these headlines ;). Maybe things like single-cell-tutorial as F1000 recommended paper, or the news about top performing data integration methods, once the paper is out.

**Pull request merged**
