### PR TITLE
simplify travis

### PR DESCRIPTION
**Pull request by flying-sheep**

### CODE REVIEW

**Comment by falexwolf** [comment]
Hm, yes it's nice that things are simpler now, but the point of the script before was to use the fast installation of the conda binaries... 

Before your commit: 3 min 46 s test time (https://travis-ci.org/theislab/scanpy/builds/454438531?utm_source=github_status&utm_medium=notification)

After your commit: 6 min 46 s test time (https://travis-ci.org/theislab/scanpy/builds/454487170?utm_source=github_status&utm_medium=notification)

While the 3 min 46 s are way too long, there is still a good chance that you realize that your commit broke everything. After almost 7 min, you're almost always doing something else already.

I also feel kind of bad about travis's servers. ;)

**Comment by falexwolf** [comment]
Well, so essentially, this PR reversed what I did quite some time ago to speed up the CI...

But, let's leave it like this. Hopefully, at some point, we'll have a less hackish way than the previous conda install script of dealing with this.

**Comment by gokceneraslan** [comment]
CircleCI claims to be super fast, can be considered maybe no?

**Comment by flying-sheep** [comment]
> Well, so essentially, this PR reversed what I did quite some time ago to speed up the CI...

Exactly! With the crucial difference that after the first build, binary packages for everything are being cached by pip, *and* now we don’t have to install conda every build.

The one you linked to was just this one initial build. The real numbers are now:

&nbsp; | Runtime | Total | Link
--- | --- | --- | ---
Before (conda) | 4m47s | 8m33s | https://travis-ci.org/theislab/scanpy/builds/454438531  
After (pip) | 3m34s | 5m 2s | https://travis-ci.org/theislab/scanpy/builds/456855724

> But, let's leave it like this. Hopefully, at some point, we'll have a less hackish way than the previous conda install script of dealing with this.

The time is now, wheee!

**Comment by falexwolf** [comment]
Oh, that's wonderful and exactly what I had hoped pip on the travis server would do! :smile: You mentioned that you might look into it at some point. I just didn't notice the 
```
cache: pip
```
line in the commit... Great that you figured this out! Test times now are really nice, in particular, as I can easily speed them up further... So cool! :smile:

**Comment by flying-sheep** [comment]
Yeah! Sorry for not explaining the change in the PR :sweat_smile:

**Pull request merged**
