### PR TITLE
fixes dendrogram issue  #1228

### PR DESCRIPTION
**Pull request by fidelram**
The PR uses `1-correlation` as distance matrix to compute the dendrogram as suggested in #1288 and mentioned in https://github.com/theislab/squidpy/pull/236

I opted for the minimal changes to the code. Other  solution would be to use `scipy.spatial.distance.pdist` that allows a larger number of distance metrics. I am open for a discussion on this topic (ping @michalk8)

### CODE REVIEW

**Comment by giovp** [comment]
Hi @fidelram ! 
looks good yes, with `distance.squareform` you are essentially transforming the corr in a condensed distance matrix right? and that's what `pdist` also passes. So I think it looks good now!
Another option would have been to pass `mean_df.T` directly to linkage, but I understand wanting to keep correlation as distances.

**Review by giovp — APPROVED** [review]

**Comment by fidelram** [comment]
Hi @giovp, basically I mimic the what the linkage code would do internally when the first argument is not a distance. Because the correlation matrix is used for `sc.tl.correlation_matrix` it is kept.

**Comment by giovp** [comment]
Makes sense! Thanks it's clear now why the corr matrix

**Review by ivirshup — CHANGES_REQUESTED** [review]
Could this get:

- [x] Bugfix release note
- [x] Links to issues that should be closed by this

**Comment by fidelram** [comment]
Issues that should be closed:
 * https://github.com/theislab/scanpy/issues/1288

**Review by ivirshup — APPROVED** [review]

**Comment by ivirshup** [comment]
@meeseeksdev backport to 1.7.x

**Comment by ivirshup** [comment]
@fidelram, in future, if you add a line like: 

```
Fixes #x, #y
```

To the initial comment in a PR, those issues will automatically be closed when the PR is merged. I think you can also link PRs to issues with the "Linked issues" element in the righthand sidebar. Using these makes it easier to tell which issues have been addressed already.

**Pull request merged**
