### PR TITLE
add utils for basis key and invert coord for spatial

### LINKED ISSUE #1463: Dots horizontally flipped in pl.embedding plot
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

I found that when plotting edges with scanpy.pl.embedding, the dots and edges do not fit together, but are horizontally flipped, like here
image
From the following minimal sample, I think that the scatterplot is wrong. 

### Minimal code sample

```python
import anndata
import numpy as np
import scanpy as sc

X = np.array([[1], [2], [3]])
pos = np.array([[1, 0], [0, 2], [0, 0]])
conn = np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]])

adata = anndata.AnnData(X=X)
adata.obsm["X_spatial"] = pos
adata.obsp["spatial_connectivity"] = conn

key_added = "spatial"
conns_key = "spatial_connectivity"
adata.uns[key_added] = {}
neighbors_dict = adata.uns[key_added]
neighbors_dict["connectivities_key"] = conns_key
neighbors_dict["distances_key"] = "dummy"

sc.pl.embedding(adata, basis="spatial", edges=True, neighbors_key="spatial", edges_width=4)
```

image

#### Versions

<details>

-----
anndata     0.7.4
scanpy      1.6.0
sinfo       0.3.1
-----
PIL                 6.2.1
anndata             0.7.4
backcall            0.2.0
cffi                1.14.0
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.1
decorator           4.4.2
get_version         2.1
google              NA
h5py                2.10.0
igraph              0.8.2
importlib_metadata  1.7.0
ipykernel           5.3.4
ipython_genutils    0.2.0
jedi                0.17.2
joblib              0.16.0
kiwisolver          1.2.0
legacy_api_wrap     1.2
leidenalg           0.8.1
llvmlite            0.34.0
louvain             0.7.0
matplotlib          3.2.1
mkl                 2.3.0
mpl_toolkits        NA
natsort             7.0.1
networkx            2.3
numba               0.51.0
numexpr             2.7.1
numpy               1.19.1
packaging           20.4
pandas              1.1.1
parso               0.7.0
pexpect             4.8.0
pickleshare         0.7.5
pkg_resources       NA
prompt_toolkit      3.0.7
ptyprocess          0.6.0
pygments            2.6.1
pyparsing           2.4.7
pytz                2020.1
scanpy              1.6.0
scipy               1.5.2
setuptools_scm      NA
sinfo               0.3.1
six                 1.15.0
sklearn             0.23.2
sphinxcontrib       NA
storemagic          NA
tables              3.6.1
texttable           1.6.2
tornado             6.0.4
traitlets           4.3.3
typing_extensions   NA
wcwidth             0.2.5
zipp                NA
zmq                 19.0.1
-----
IPython             7.16.1
jupyter_client      6.1.6
jupyter_core        4.6.3
-----
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) [GCC 7.3.0]
Linux-4.15.0-118-generic-x86_64-with-debian-buster-sid
4 logical CPU cores, x86_64
-----

</details>

### PR DESCRIPTION
**Pull request by giovp**
Addresses #1463 , also added a util function to pick the right basis (before `_utils.plot_edges` and `_utils.plot_arrows` could only handle basis starting with X)

### CODE REVIEW

**Comment by giovp** [comment]
the code provided by @SabrinaRichter now works:

```python
X = np.array([[1], [2], [3]])
pos = np.array([[1, 0], [0, 2], [0, 0]])
conn = np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]])

adata_temp = anndata.AnnData(X=X)
adata_temp.obsm["spatial"] = pos
adata_temp.obsp["spatial_connectivity"] = conn

key_added = "spatial"
conns_key = "spatial_connectivity"
adata_temp.uns[key_added] = {}
neighbors_dict = adata_temp.uns[key_added]
neighbors_dict["connectivities_key"] = conns_key
neighbors_dict["distances_key"] = "dummy"

sc.pl.embedding(adata_temp, basis="spatial", edges=True, neighbors_key="spatial", edges_width=4)
```

image

**Comment by giovp** [comment]
@Koncopd can I merge this?

**Comment by Koncopd** [comment]
Sry for for the delay, i'll check soon.

**Comment by fidelram** [comment]
Looks good to me.

**Pull request merged**
