### PR TITLE
Add CIARA algorithm to ecosystem page

### PR DESCRIPTION
**Pull request by stkmrc**
As discussed with Isaac today, here's a pull request to list our CIARA package (working with AnnData objects) for rare cell type identification from scRNA-Seq data to the scanpy ecosystem page.

### CODE REVIEW

**Comment by ivirshup** [comment]
Thanks @stkmrc!

Could you merge master into this PR? It looks like there was a dependency issue that should be fixed now.

**Comment by stkmrc** [comment]
@ivirshup Sure, here you go.

**Comment by ivirshup** [comment]
Thanks for that.

From the tutorial, this seems like a feature selection method. Is that a reasonable assessment? Just trying to figure out if it might fit into one of the existing categories.

**Comment by stkmrc** [comment]
@ivirshup Yes in general, I agree. But we want to advertise it mainly for the use case of identifying rare cell types. If somebody looks for an approach to do so, I am sure it would be easier to also find on the ecosystem page under this new category, instead of checking all more general feature selection methods.

**Comment by ivirshup** [comment]
Could the description mention that it does feature selection?

Like "CIARA is a feature selection method for rare cell type identification"?

**Comment by stkmrc** [comment]
Sounds good. So whats your suggestion on how to proceed?

**Comment by stkmrc** [comment]
@ivirshup I now placed it under the feature selection category, added a description and switched from the .rst to .md file as this has changed in the master branch. Could you please accept the PR it as quick as possible, before the master branch changes again? Thank you!

**Comment by ivirshup** [comment]
Looks good! I had meant to get that done myself, but thanks for getting to it first!

**Pull request merged**
