### PR TITLE
Fix for double log in fold-changes and for indexing in wilcoxon test

### PR DESCRIPTION
**Pull request by a-munoz-rojas**
This is a fix for the issue discussed in #517. I implemented it by adding a new parameter to indicate whether the data in `adata.X` is log-transformed or not, and set it to True as a default, assuming most users will have log-transomed data at this point. This fix is assuming the transformation was done with log1p, as in `sc.pp.log1p.` The matrix is transformed back to raw counts only for the fold-change calculations - everything else is left the same to maintain the tests in log-space.

I also included a fix for a bug in the indexing that was implemented in the original chunking for the wilcoxon test. This was noted in #469 and the same fix is implemented in PR #471 - thanks for catching that bug!

### CODE REVIEW

**Comment by falexwolf** [comment]
Hey @a-munoz-rojas and @LuckyMD! Thank you for this!

However, I think this adds a lot of code and computational burden. I'd prefer to make an approximation, which is similar to interchanging log mean with mean log.

`x1` and `x2` are two arrays storing count values.
```
log2FC(x1, x2) = log2(mean(x1) / mean(x2)) = log2(mean(x1)) - log2(mean(x2)) = (log(mean(x1)) - log(mean(x1))) / log(2)
```
In Scanpy, we typically store `log1p(x)` in the data matrix. For the tests, we have already computed `mean(log1p(x))`. Hence, the following expression is a one-line edit. 
```
log2FCapprox = log2((expm1(mean(log1p(x1))) / expm1(mean(log1p(x2))))
```
Obviously, this is an approximation; high values in `x` are down-weighted by virtue of computing a mean that's weighted with a `log1p`. The resulting `mean(log1p(x))` is therefore rigorously smaller than `log1p(mean(x))`; if you don't have a lot of outliers, then there will be little difference. If there is a lot of variance, there will be a difference. As one has the same effect both in the numerator and denominator, some of this will cancel out. Hence, one gets an estimator for "effect strength" (after all, this is what we are interested in, that is very similar to `log2FC`, but more robust to outliers.

I'd prefer this, I have to admit, together with a note in the docs.

**Comment by LuckyMD** [comment]
I reckon that's a fair consideration. In the end we don't use `sc.tl.rank_genes_groups()` for complex DE tests that require this amount of detail, but instead for marker gene calculations where it's mainly about ranking genes. It would be interesting to see the error of the approximation though.

**Comment by a-munoz-rojas** [comment]
Hey @falexwolf, thanks for your note. I apologize for the late reply - I was away at a conference and had little time to work on this. 
I agree that this is a cleaner way of doing this and will be more robust to outliers, even if it's at the expense of the approximation. Like @LuckyMD mentioned, this function is generally used for more basic differential testing, so further exploration of differential expression can rely on more complicated downstream analysis. Out of curiosity, I'll also calculate what the error of the approximation is, just to have an idea.

I'm a little limited in bandwidth at the moment, but this is an easy change that I should be able to implement this week. Sorry for the delay - I'll submit the changes soon!

**Comment by falexwolf** [comment]
Thank you very much, @a-munoz-rojas!

**Comment by a-munoz-rojas** [comment]
Hey, sorry for the delayed response. I just pushed the new version with the changes we discussed. I also checked what the error looked like - it's pretty close for most of the cases (I'm attaching a plot with estimated (mean-log) vs "actual" (log-mean) fold changes - as expected, only in the extremes do we start to get a little bit of an underestimation. In my dataset, I got a mean error of about 3%, with the largest error seen in genes with extreme outliers as we expected (the attached violin plot has the largest error, ~70% lower.  
[test_meanlogerror.pdf](https://github.com/theislab/scanpy/files/3000658/test_meanlogerror.pdf)
[violintest_outlier.pdf](https://github.com/theislab/scanpy/files/3000659/violintest_outlier.pdf)

**Comment by falexwolf** [comment]
Thank you, this looks good! I'm merging it. :)

**Comment by gokceneraslan** [comment]
@a-munoz-rojas I'm getting the following warning:

```
/home/user/Code/scanpy/scanpy/tools/_rank_genes_groups.py:203: RuntimeWarning: overflow encountered in expm1
  foldchanges = (np.expm1(means[igroup]) + 1e-9) / (np.expm1(mean_rest) + 1e-9) #add small value to remove 0's
```

Any ideas?

**Comment by gokceneraslan** [comment]
Here is another one:

```
/home/user/Code/scanpy/scanpy/tools/_rank_genes_groups.py:203: RuntimeWarning: invalid value encountered in true_divide
  foldchanges = (np.expm1(means[igroup]) + 1e-9) / (np.expm1(mean_rest) + 1e-9) #add small value to remove 0's
```

**Comment by gokceneraslan** [comment]
Also `log_transformed=True` parameter is not listed in the documentation.

**Comment by gokceneraslan** [comment]
Wait, where exactly is `log_transformed` used in the code?

**Comment by falexwolf** [comment]
`log_transformed` disappeared in the last commit here...

Better: `pp.log1p` should write an attribute to `.uns`, say simply `.uns['log1p'] = True`. Depending on that attribute, log2fc is computed by rexponaniating or not.

Also: If trying to call a t-test with non-logarithmized data, a warning should be written.

The overflow and 0 warnings: are you sure you used logarithmized data, Gökcen?

**Comment by gokceneraslan** [comment]
> Better: `pp.log1p` should write an attribute to `.uns`, say simply `.uns['log1p'] = True`. Depending on that attribute, log2fc is computed by rexponaniating or not.

Fully agree.

> 
> Also: If trying to call a t-test with non-logarithmized data, a warning should be written.
> 

Also agree.

> The overflow and 0 warnings: are you sure you used logarithmized data, Gökcen?

Oh true, it wasn't log transformed, true.

**Comment by falexwolf** [comment]
Ok, good to read that it wasn't log-transformed!

@Koncopd, could you quickly implement these simple changes? Before continuing to work on the UMAP? These simple changes are for 1.4.1, the UMAP will be for 1.5. Thank you!

**Pull request merged**
