### PR TITLE
address few docs issues

### LINKED ISSUE #827: scanpy.api.tl.diffmap documentation
Please consider mentioning explicitly in the documentation of [`scanpy.api.tl.diffmap`](https://scanpy.readthedocs.io/en/stable/api/scanpy.api.tl.diffmap.html#scanpy.api.tl.diffmap) that _"the 0-th column is the steady-state solution, which is non-informative in diffusion maps",_ as mentioned here: https://github.com/theislab/single-cell-tutorial/blob/master/latest_notebook/Case-study_Mouse-intestinal-epithelium_1906.ipynb. Also that it's not plotted by default, cf. https://github.com/theislab/scanpy/issues/675.

It is very important for those who want to use these coordinates (`adata.obsm["X_diffmap"]`).

### LINKED ISSUE #1434: Insufficient explanation in docs about n_genes_by_counts variable
Hi, 

Thanks for developing a good tool for analyzing scRNAseq data. In the process of learning scRNAseq analysis with scanpy I have come across a few places in the documentation that left me a bit confused. 

The most confusing is that I could not find a description for the variable `n_genes_by_counts` calculated by the function scanpy.pp.calculate_qc_metrics and mentioned in the tutorial https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html. 

I asked a question about this in [the discourse](https://scanpy.discourse.group/t/clarification-of-qc-metrics/295) and was asked to open a github issue. 

I guess an explanation for the docs could be something like `n_genes_by_counts: The number of genes with at least 1 count in a cell. Calculated for all cells.` 

Since I am writing this I might add that I did not understand exactly how the normalization function [scanpy.pp.normalize_total](https://scanpy.readthedocs.io/en/stable/api/scanpy.pp.normalize_total.html) works before I stumbled upon the description of the deprecated function with the same purpose: [scanpy.pp.normalize_per_cell](https://scanpy.readthedocs.io/en/stable/api/scanpy.pp.normalize_per_cell.html) . The deprecated function has a helpful line saying: `Normalize each cell by total counts over all genes, so that every cell has the same total count after normalization.` which at least helped me clear things up. Maybe this line should be added to the new version of the function?

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

### LINKED ISSUE #1675: make pinndescent as part of requirements? (or at least document better)
- [ ] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

in the last months there's been several people raising issues about `sc.pp.neighbors` being very slow. After pointing them to installing `pynndescent` they noticed considerable improvements in run times.
pynndescent is still top of the benchmarks afaik https://github.com/lmcinnes/pynndescent

Problems are that:
- afaik there's nowhere in the docs where this is documented
- it might be a good idea to just add it as default?

pinging @Koncopd @ivirshup , happy to add a line about pynndescent, just need to know where.

### PR DESCRIPTION
**Pull request by giovp**
This PR aims at closing couple of open issues related to docs. Pinging original users who opened the issues.

- closes #1675 add pynndescent note (me)
- closes #1434 clarify qc metric and normalize total @havardtl
- closes #827 clarify diff component indexing @veghp

### CODE REVIEW

**Comment by ivirshup** [comment]
LGTM. 

Sorry about the conflicts! Might be worth a rebase.

**Comment by ivirshup** [comment]
Oops, forgot to ask for a release note

**Comment by giovp** [comment]
@ivirshup sorry late on this:
- shall I do it in a new PR?
- do I need to backport with meeksbot ? (also, was wodneirng how to use that).

Thank you!

**Comment by ivirshup** [comment]
* Release note, yeah,  a new PR.
* Backport, up to you. Docs should be fine to backport. [Instructions here](https://scanpy.readthedocs.io/en/latest/dev/versioning.html), but you basically just need to write a comment with the right format and a backport PR will be opened.

**Comment by giovp** [comment]
adding release note in #1740

**Pull request merged**
