### PR TITLE
(fix): sort pca test args

### PR DESCRIPTION
**Pull request by ilan-gold**
Since `gen_pca_params` is a generator, not sure how we can control the order besides rolling back the use of sets.  So I landed on just sorting the args based on `id` of the pytest.  

I was running in to https://github.com/pytest-dev/pytest-xdist/issues/432

- [ ] Closes #
- [x] Tests included or not required because:

- [x] Release notes not necessary because: just fixing some tests

### CODE REVIEW

**Comment by flying-sheep** [comment]
Would probably be more elegant to just do this in the generator instead:

```diff
-for svd_solver in svd_solvers:
+for svd_solver in sorted(svd_solvers):
```

That being said, there are ordered sets in Python, they’re just hidden:

```py
def ordered_union(a: KeysView[T1], b: KeysView[T2]) -> KeysView[T1 | T2]:
    """Ordered set union
    
    Examples
    --------
    >>> ordered_union(dict.fromkeys("ab").keys(), dict.fromkeys("cb").keys())
    dict_keys(['a', 'b', 'c'])
    """    
    return (dict.fromkeys(a) | dict.fromkeys(b)).keys()
```

**Review by flying-sheep — CHANGES_REQUESTED** [review]
Would probably be more elegant to just do this in the generator instead:

```diff
-for svd_solver in svd_solvers:
+for svd_solver in sorted(svd_solvers):
```

That being said, there are ordered sets in Python, they’re just hidden:

```py
def ordered_union(a: KeysView[T1], b: KeysView[T2]) -> KeysView[T1 | T2]:
    """Ordered set union
    
    Examples
    --------
    >>> ordered_union(dict.fromkeys("cb").keys(), dict.fromkeys("ca").keys())
    dict_keys(['c', 'b', 'a'])
    """    
    return dict.fromkeys(a) | dict.fromkeys(b)
```

**Comment by ilan-gold** [comment]
@flying-sheep `SVDSolver` can be a union of literals so any sort of sorting on it is not out-of-the-box from what I can tell

**Comment by flying-sheep** [comment]
`svd_solvers` is just a `set[str]`, no?

/edit: oof it isn’t:

```py
>>> from typing import Literal, get_args
>>> get_args(Literal["a"] | Literal["b"])
(typing.Literal['a'], typing.Literal['b'])
```

I was sure these get collapsed into one `Literal` … that’s a bug!

**Review by flying-sheep — APPROVED** [review]

**Pull request merged**
