### PR TITLE
Fix download path of pbmc3k_processed

### LINKED ISSUE #1471: sc.datasets.pbmc3k_processed() returns 404
The download of the anndata object of the pbmc_3k_processed dataset doesn't work, as the branch from which the object should be downloaded from changed from `master` to `main`.

https://github.com/theislab/scanpy/blob/256f5944cd03fc0b8b510d607502d7170f8e5813/scanpy/datasets/_datasets.py#L305

### PR DESCRIPTION
**Pull request by danielStrobl**
The name of the `master` branch of the `cellxgene` repo changed to `main`. This results in a 404 error when trying to download the pbmc3k_processed dataset (see https://github.com/theislab/scanpy/issues/1471). This PR fixes that.

### CODE REVIEW

**Comment by LuckyMD** [comment]
I'm guessing this should also be added to the release notes @Koncopd?

**Comment by Koncopd** [comment]
Yes, also the problem is that i can't merge it because travis is stuck for some reason.

**Comment by z5ouyang** [comment]
Even I changed it manually, still error with CERTIFICATE_VERIFY_FAILED:

```
>>> import scanpy as sc
>>> adata_ref = sc.datasets.pbmc3k_processed()
pbmc3k_processed.h5ad: 0.00B [00:00, ?B/s]
Traceback (most recent call last):
  File "/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/anaconda3/envs/scIB-python/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/anaconda3/envs/scIB-python/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/anaconda3/envs/scIB-python/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/anaconda3/envs/scIB-python/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/anaconda3/envs/scIB-python/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/anaconda3/envs/scIB-python/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/anaconda3/envs/scIB-python/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/anaconda3/envs/scIB-python/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/anaconda3/envs/scIB-python/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/scIB-python/lib/python3.7/site-packages/scanpy/datasets/_utils.py", line 10, in wrapper
    return f(*args, **kwargs)
  File "/anaconda3/envs/scIB-python/lib/python3.7/site-packages/scanpy/datasets/_datasets.py", line 305, in pbmc3k_processed
    backup_url='https://raw.githubusercontent.com/chanzuckerberg/cellxgene/main/example-dataset/pbmc3k.h5ad',
  File "/anaconda3/envs/scIB-python/lib/python3.7/site-packages/scanpy/readwrite.py", line 122, in read
    **kwargs,
  File "/anaconda3/envs/scIB-python/lib/python3.7/site-packages/scanpy/readwrite.py", line 694, in _read
    is_present = _check_datafile_present_and_download(filename, backup_url=backup_url,)
  File "/anaconda3/envs/scIB-python/lib/python3.7/site-packages/scanpy/readwrite.py", line 970, in _check_datafile_present_and_download
    _download(backup_url, path)
  File "/anaconda3/envs/scIB-python/lib/python3.7/site-packages/scanpy/readwrite.py", line 936, in _download
    urlopen(Request(url, headers={"User-agent": "scanpy-user"})) as resp:
  File "/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
```

**Comment by gokceneraslan** [comment]
@danielStrobl Do you mind pushing another commit (like anything), just to trigger Travis? It seems like it’s stuck.

**Comment by danielStrobl** [comment]
Ok, looks like travis has run through now.

**Pull request merged**
