### PR TITLE
Phenograph supporting Leiden clustering

### PR DESCRIPTION
**Pull request by awnimo**
An updated new release of [`PhenoGraph`](https://github.com/dpeerlab/PhenoGraph) package now supports `Leiden` algorithm for community detection. The suggested changes in `scanpy/external/tl/_phenograph.py` will make the new updates visible in Scanpy as well. Also, the suggested changes include a testing function in `scanpy/tests/external/test_phenograph.py`, and updated docs.

### CODE REVIEW

**Comment by awnimo** [comment]
Hi @flying-sheep ,
Please review and let me know if anything needs to be done here.

Thank you

**Comment by Koncopd** [comment]
@awnimo , for me test_phenograph.py fails with `E   TypeError: Expected list, got numpy.ndarray`.
Could you check please?
This is certainly related to scipy 1.5. With scipy 1.4 the test works fine.

**Comment by awnimo** [comment]
> @awnimo , for me test_phenograph.py fails with `E TypeError: Expected list, got numpy.ndarray`.
> Could you check please?
> This is certainly related to scipy 1.5. With scipy 1.4 the test works fine.

Indeed, this error is related to scipy, and we have fixed that in Phenograph new release [1.5.7](https://github.com/dpeerlab/PhenoGraph#version-157).

The `test_phenograph.py` does not fail with the new Phenograph release (`pip install -U phenograph`)

**Comment by Koncopd** [comment]
@awnimo ok, i see, thanks.
Also for some reason this pr deletes docs/api/scanpy.external.rst

**Comment by awnimo** [comment]
@Koncopd 
This is weird never noticed. How can I restore it??
I only built the docs for me to test the outputs. Could be that building the docs affected somehow docs/api/scanpy.external.rst??

**Comment by Koncopd** [comment]
@awnimo i'm not sure how to restore it, there were so many commits so git reset won't help.

Hm, you can try copying this file back and commiting.

**Comment by awnimo** [comment]
@Koncopd 
I added back docs/api/scanpy.external.rst.

**Pull request merged**
