### PR TITLE
n_pcs are no longer ignored for representations other than "X_pca"

### LINKED ISSUE #1846: sc.pp.neighbors n_pcs doesn't subset if use_rep isn't X_pca
Smaller reproducible example below: https://github.com/theislab/scanpy/issues/1846#issuecomment-863823148 –@ivirshup

--------------------------

- [x] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

Hi, 

not sure whether this is the right place to post this but i'm having a slight issue after running harmony from scanpy. It's producing very different results and i'm not sure why. It didn't used to be a problem when i was using scanpy 1.6x

### Minimal code sample (that we can copy&paste without having any data)

without running harmony:
```python
sc.tl.pca(adata, svd_solver='arpack')
sc.pp.neighbors(adata, n_pcs = 20)
sc.tl.umap(adata)
sc.pl.umap(adata, color = 'sample')
```
image

with harmony
```python
adata1 = adata.copy()
sc.external.pp.harmony_integrate(adata1, key = 'sample')
sc.pp.neighbors(adata1, n_pcs = 20, use_rep = 'X_pca_harmony')
sc.tl.umap(adata1)
sc.pl.umap(adata1, color = 'sample')
```
image

If i don't use harmony and just ran with `n_pcs = 50`, the result is similar.
```python
adatax = adata.copy()
sc.pp.neighbors(adatax, n_pcs = 50)
sc.tl.umap(adatax, min_dist = .3)
sc.pl.umap(adatax, color = 'sample')
```
image

What i don't get is, why does the following work then?
```python
# my current workaround
adata2 = adata.copy()
sc.external.pp.harmony_integrate(adata2, key = 'sample', adjusted_basis='X_pca')
sc.pp.neighbors(adata2, n_pcs = 20)
sc.tl.umap(adata2)
sc.pl.umap(adata2, color = 'sample')
```
image

#### Versions

<details>

-----
anndata     0.7.5
scanpy      1.7.1
sinfo       0.3.1
-----
Bio                 1.78
PIL                 8.2.0
adjustText          NA
anndata             0.7.5
annoy               NA
backcall            0.2.0
brotli              NA
cachecontrol        0.12.6
cairo               1.19.1
certifi             2020.06.20
cffi                1.14.5
changeo             1.0.2
chardet             4.0.0
cloudpickle         1.6.0
cycler              0.10.0
cython_runtime      NA
dandelion           0.1.2
dask                2021.03.0
dateutil            2.8.1
decorator           5.0.6
descartes           NA
distance            NA
get_version         2.1
google              NA
h5py                2.10.0
harmonypy           NA
hdmedians           NA
idna                2.10
igraph              0.8.3
ipykernel           5.3.4
ipython_genutils    0.2.0
ipywidgets          7.6.3
jedi                0.17.0
joblib              1.0.1
kiwisolver          1.3.1
legacy_api_wrap     1.2
leidenalg           0.8.3
llvmlite            0.34.0
matplotlib          3.3.4
mizani              0.7.2
mpl_toolkits        NA
msgpack             1.0.2
natsort             7.1.1
networkx            2.5
numba               0.51.2
numexpr             2.7.1
numpy               1.20.2
packaging           20.9
palettable          3.3.0
pandas              1.2.4
parso               0.8.2
patsy               0.5.1
pexpect             4.8.0
pickleshare         0.7.5
pkg_resources       NA
plotnine            0.7.1
polyleven           NA
presto              0.6.2
prompt_toolkit      3.0.17
ptyprocess          0.7.0
pycparser           2.20
pygments            2.8.1
pynndescent         0.5.2
pyparsing           2.4.7
pytoml              NA
pytz                2021.1
pywt                1.1.1
requests            2.25.1
scanpy              1.7.1
scipy               1.6.3
scrublet            NA
seaborn             0.11.1
setuptools_scm      NA
sinfo               0.3.1
six                 1.15.0
skbio               0.5.6
skimage             0.18.1
sklearn             0.23.2
socks               1.7.1
sparse              0.11.2
sphinxcontrib       NA
statsmodels         0.12.1
storemagic          NA
tables              3.6.1
texttable           1.6.3
tlz                 0.11.1
toolz               0.11.1
tornado             6.1
tqdm                4.59.0
traitlets           5.0.5
typing_extensions   NA
umap                0.5.1
urllib3             1.26.4
wcwidth             0.2.5
yaml                5.4.1
zmq                 20.0.0
-----
IPython             7.22.0
jupyter_client      6.1.12
jupyter_core        4.7.1
notebook            6.3.0
-----
Python 3.8.8 (default, Feb 24 2021, 21:46:12) [GCC 7.3.0]
Linux-4.15.0-142-generic-x86_64-with-glibc2.10
64 logical CPU cores, x86_64
-----
Session information updated at 2021-05-19 16:44

</details>

### PR DESCRIPTION
**Pull request by PGmajev**
Hello scanpy team,

this is my first pull request, I hope I at least vaguely adhered to your contribution guidelines. I did not find an issue tackling this exact situation, but if I overlooked it, feel free to point that out.

This PR changes few lines of code involved in getting dimensionality reductions like X_pca. The current code skips subsetting the respective array to the n_pcs requested, if the representation name is not X_pca. I do not think this is optimal.

This change allows to only take the dimensions needed also for non X_pca representations. This can be useful when using harmony for example or storing different PCA embeddings in the same object. Then it is not needed to first store them as X_pca to be able to properly use the n_pcs parameter in e.g. pp.neighbors. It might make sense then to adapt the documentation respectively as well.

----------

Fixes #1846

### CODE REVIEW

**Review by ivirshup — CHANGES_REQUESTED** [review]
Thanks for the PR! This should close #1846.

Could you add a test for this?  Could you add a test showing this argument now works for some function? E.g. if you copy pca to a different key in `obsm`, `n_pcs` will still be used.

**Comment by ivirshup** [comment]
@PGmajev, I would recommend setting up pre-commit for the repo (as described in the contributing guide [here](https://scanpy.readthedocs.io/en/latest/dev/getting-set-up.html#pre-commit)). It should save you from dealing with these formatting errors.

**Comment by PGmajev** [comment]
Hey @ivirshup,

thank you for your reply. I was not aware of that issue, but yes, this PR should solve it.

I did not know where and how exactly you would prefer the test to be. So for now I put it in test_pca.py and I run a full pca on the pbmc3k data. This might of course be a bit much. Shall I provide and/or use some even smaller sample data?

**Comment by PGmajev** [comment]
@ivirshup Thank you very much for the advice regarding pre-commit, I will use it

**Comment by PGmajev** [comment]
I think I implemented all requested changes now. Sorry it took a bit longer and quite a number of commits. If there is anything else I can/should do, please let me know

**Comment by ivirshup** [comment]
No worries. 

Right now I'm just thinking of whether this should be called `n_dims` now, and trying to figure out why I have the sneaking suspicion that this broke something last time I looked at it.

One last thing from you, could you add a release note to `docs/release-notes/1.9.0.md`?

**Comment by PGmajev** [comment]
@ivirshup Thank you for the feedback. I will add a release note soon.

I also thought about the naming of the parameter. However, if we assume that also in the future it is mostly used to subset the number of PCs in PCA arrays stored under different names, it should be fine?

I can not comment further on what these changes may break, at least ideally they should make the use of n_pcs more consistent and as expected. Would you suggest, I implement some further, more comprehensive tests?

**Comment by ivirshup** [comment]
I think you're all good. Taking another look at the function I believe I had actually tried to completely replace the whole thing (since the logic is fairly convoluted), which ended up breaking functions that relied on the convoluted parts.

I think ultimately the whole function should be replaced, ideally using `sc.get._get_obs_rep`. At that point we can rename the argument and make it more widely available.

**Review by ivirshup — APPROVED** [review]

**Comment by adamgayoso** [comment]
@ivirshup @Zethson  This is a pretty big breaking change. Can we revert this? `n_pcs` shouldn't change but we can introduce a new arg and then deprecate n_pcs? It's a bad name anyway

**Pull request merged**
