### PR TITLE
Added marker parameter to scatter plots

### LINKED ISSUE #2122: Can't change the marker style with sc.pl.embedding()
- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [x] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

Hello !

I'm not sure whether this is a bug or it is enforced intentionally but even though users can use the kwargs to pass on to `sc.pl.embedding` any additional argument for `matplotlib.pyplot.scatter()`, trying to change the marker style doesn't work. As you can see below, the marker style is hardcoded in `sc.pl.embedding` to always be "." thus raising an error when trying to use another marker style due to `scatter()` being fed with the keyword argument `marker` multiple times.
Best,

Jules

### Minimal code sample (that we can copy&paste without having any data)

```python
import scanpy as sc
import anndata

adata = anndata.AnnData(X=np.random.rand(1000, 20))
sc.pp.neighbors(adata)
sc.tl.umap(adata, min_dist=0.2)
sc.pl.umap(adata,show=True, marker="^")
```

```pytb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_10129/876858932.py in <module>
      5 sc.pp.neighbors(adata)
      6 sc.tl.umap(adata, min_dist=0.2)
----> 7 sc.pl.umap(adata,show=True, marker="^")

~/miniconda3/envs/uhler/lib/python3.7/site-packages/scanpy/plotting/_tools/scatterplots.py in umap(adata, **kwargs)
    657     tl.umap
    658     """
--> 659     return embedding(adata, 'umap', **kwargs)
    660 
    661 

~/miniconda3/envs/uhler/lib/python3.7/site-packages/scanpy/plotting/_tools/scatterplots.py in embedding(adata, basis, color, gene_symbols, use_raw, sort_order, edges, edges_width, edges_color, neighbors_key, arrows, arrows_kwds, groups, components, layer, projection, scale_factor, color_map, cmap, palette, na_color, na_in_legend, size, frameon, legend_fontsize, legend_fontweight, legend_loc, legend_fontoutline, vmax, vmin, vcenter, norm, add_outline, outline_width, outline_color, ncols, hspace, wspace, title, show, save, ax, return_fig, **kwargs)
    383                 rasterized=settings._vector_friendly,
    384                 norm=normalize,
--> 385                 **kwargs,
    386             )
    387 

TypeError: functools.partial object got multiple values for keyword argument 'marker'
```

#### Versions

<details>

WARNING: If you miss a compact list, please try `print_header`!
The `sinfo` package has changed name and is now called `session_info` to become more discoverable and self-explanatory. The `sinfo` PyPI package will be kept around to avoid breaking old installs and you can downgrade to 0.3.2 if you want to use it without seeing this message. For the latest features and bug fixes, please install `session_info` instead. The usage and defaults also changed slightly, so please review the latest README at https://gitlab.com/joelostblom/session_info.
-----
anndata     0.7.6
scanpy      1.8.1
sinfo       0.3.4
-----
PIL                         8.3.2
backcall                    0.2.0
beta_ufunc                  NA
binom_ufunc                 NA
cached_property             1.5.2
cffi                        1.14.6
cloudpickle                 2.0.0
colorama                    0.4.4
cycler                      0.10.0
cython_runtime              NA
dask                        2021.09.1
dateutil                    2.8.2
debugpy                     1.5.0
decorator                   5.1.0
defusedxml                  0.7.1
entrypoints                 0.3
fsspec                      2021.10.0
google                      NA
h5py                        3.4.0
ipykernel                   6.4.1
ipython_genutils            0.2.0
ipywidgets                  7.6.5
jedi                        0.18.0
jinja2                      3.0.2
joblib                      1.1.0
kiwisolver                  1.3.2
llvmlite                    0.37.0
markupsafe                  2.0.1
matplotlib                  3.4.3
matplotlib_inline           NA
mpl_toolkits                NA
mudata                      0.1.0
muon                        0.1.1
natsort                     7.1.1
nbinom_ufunc                NA
numba                       0.54.1
numexpr                     2.7.3
numpy                       1.20.3
packaging                   21.0
pandas                      1.3.3
parso                       0.8.2
pexpect                     4.8.0
pickleshare                 0.7.5
pkg_resources               NA
prompt_toolkit              2.0.10
psutil                      5.9.0
ptyprocess                  0.7.0
pycparser                   2.20
pydev_ipython               NA
pydevconsole                NA
pydevd                      2.4.1
pydevd_concurrency_analyser NA
pydevd_file_utils           NA
pydevd_plugins              NA
pydevd_tracing              NA
pygments                    2.10.0
pynndescent                 0.5.4
pyparsing                   2.4.7
pyreadr                     0.4.4
pytz                        2021.3
scipy                       1.7.1
seaborn                     0.11.2
six                         1.16.0
sklearn                     1.0
sphinxcontrib               NA
statsmodels                 0.13.0
storemagic                  NA
tables                      3.6.1
threadpoolctl               3.0.0
tlz                         0.11.1
toolz                       0.11.1
tornado                     6.1
tqdm                        4.62.3
traitlets                   5.1.0
typing_extensions           NA
umap                        0.5.1
wcwidth                     0.2.5
yaml                        5.4.1
zipp                        NA
zmq                         22.3.0
-----
IPython             7.28.0
jupyter_client      7.0.6
jupyter_core        4.8.1
notebook            6.4.4
-----
Python 3.7.2 (default, Dec 29 2018, 06:19:36) [GCC 7.3.0]
Linux-4.15.0-70-generic-x86_64-with-debian-buster-sid
4 logical CPU cores, x86_64
-----
Session information updated at 2022-01-25 10:12

</details>

### PR DESCRIPTION
**Pull request by ArianAmani**
fixed #2122 
This [issue](https://github.com/scverse/scanpy/issues/2122) was really bothering me as I had to switch to matplotlib for custom markers and it made my code inconsistent.
I added the parameter to use specific markers instead of always using `'.'`. The default is still `'.'` and easily changeable using param: `marker`
Examples:
`sc.pl.umap(adata, color='random_group', size=300)`
image

`sc.pl.umap(adata, color='random_group', size=300, marker='x')`
image

`sc.pl.umap(adata, color=['random_group', 'second_random_group'], size=300)`
image

`sc.pl.umap(adata, color=['random_group', 'second_random_group'], size=300, marker='^')`
image

`sc.pl.umap(adata, color=['random_group', 'second_random_group'], size=300, marker=['x', '^'])`
image

### CODE REVIEW

**Review by flying-sheep — COMMENTED** [review]
Nice! Needs some testing though to make sure it works (e.g. specifying a sequence of markers)

You should also make sure the types are correct: `Optional[X]` means `X | None`. Is `None` a valid option? Does it make sense that the type is different in multiple spots? (`Optional[Sequence[str]]` vs `Union[str, Sequence[str], None]` vs `Union[str, Sequence[str]]`)

**Review by flying-sheep — CHANGES_REQUESTED** [review]
Nice! Needs some testing though to make sure it works (e.g. specifying a sequence of markers)

You should also make sure the types are correct: `Optional[X]` means `X | None`. Is `None` a valid option? Does it make sense that the type is different in multiple spots? (`Optional[Sequence[str]]` vs `Union[str, Sequence[str], None]` vs `Union[str, Sequence[str]]`)

**Comment by ArianAmani** [comment]
> Nice! Needs some testing though to make sure it works (e.g. specifying a sequence of markers)
> 
> You should also make sure the types are correct: `Optional[X]` means `X | None`. Is `None` a valid option? Does it make sense that the type is different in multiple spots? (`Optional[Sequence[str]]` vs `Union[str, Sequence[str], None]` vs `Union[str, Sequence[str]]`)

You're absolutely right about the types. I changed the types such as all are accepting the same `Union[str, Sequence[str]]` now.
I also tested several situations I could think of, in [this notebook](https://colab.research.google.com/drive/1ltg0Qs_dlxS_RMuN7z1DdLLV7VLBtZtd?usp=sharing) and they all worked fine.

If any more tests (different situations) are needed, please let me know.

**Comment by flying-sheep** [comment]
I’m talking about unit test. please add one here.

You can just add one or more parameter sets to the list, and the test will create a file at `scanpy/tests/figures/master_{id}.png`.
Just copy that file to `scanpy/tests/_images/` and commit it together with the added test.

https://github.com/scverse/scanpy/blob/9c6996f374370a7d50768c634e76e50173d22839/scanpy/tests/test_plotting.py#L973-L1082

if you need help, please tell us!

**Comment by ArianAmani** [comment]
Thanks for the reference, I added a number of tests to where you mentioned. I also changed the `broadcasting` method for `markers` so now it has the same process as `color` and `dimensions`, and therefore if broadcasting fails, the output error is more understandable (same as when `color` and `dimensions` broadcasting fails). I also added a test for `marker broadcasting`.

**Review by flying-sheep — APPROVED** [review]
That’s wonderful!

**Pull request merged**
