### PR TITLE
Add a Codacy badge to README.rst

### PR DESCRIPTION
**Pull request by codacy-badger**

### CODE REVIEW

**Comment by flying-sheep** [comment]
Thank you bot.

@theislab/scanpy I think that app can help us eliminate duplicate code and other code smells: https://app.codacy.com/project/theislab/scanpy/dashboard

**Comment by Zethson** [comment]
Would merging this PR enable PR checks with codacy?

**Comment by ivirshup** [comment]
I don't like codacy, it's really flaky with its checks (e.g. errors appear and disappear at random). That's why we disabled it in the first place.

**Comment by Zethson** [comment]
Then I would close this PR

**Pull request closed without merging**
