### PR TITLE
fix default size of spot

### LINKED ISSUE #1253: Scanpy spatial bug in visualisation defaults
Looks like the default values for plotting Visium spots are way outsized.

Try this in your lymph node notebook:
```python
sc.pl.spatial(adata, img_key = "hires", cmap='magma',
              color=['total_counts', 'n_genes_by_counts'],
              gene_symbols='SYMBOL')
```
This is what I get:
...
image

#### Versions:
scanpy==1.5.1 anndata==0.7.1 umap==0.3.10 numpy==1.17.3 scipy==1.4.1 pandas==0.25.3 scikit-learn==0.22.1 statsmodels==0.10.2 python-igraph==0.7.1 louvain==0.6.1 leidenalg==0.7.0

### PR DESCRIPTION
**Pull request by giovp**
Closes #1253

### CODE REVIEW

**Comment by ivirshup** [comment]
This seems like a very drastic change for default output, I feel like this deserves a test.

Any idea what happened here? I'm very surprised this wasn't caught by a test or the tutorials.

**Comment by giovp** [comment]
Sorry for late reply, wasn't catched by the previous test because the test set the size of the spot for plotting.
Current test:
```python
sc.pl.spatial(
        adata,
        color="array_row",
        groups=["24", "33"],
        crop_coord=(100, 400, 400, 100),
        alpha=0.5,
        size=1.3,
    )
```
Shall i remove the `size` param from this test or make a new one?

**Comment by giovp** [comment]
hi @ivirshup, any news on this? It's really a minor thing.

**Comment by ivirshup** [comment]
Sorry for taking a while to get back on this!

It would be good if there was separate case for plotting with default values.

**Comment by giovp** [comment]
@ivirshup sorry super late on this, added a default test.

**Review by ivirshup — APPROVED** [review]
No worries! LGTM.

**Pull request merged**
