### PR TITLE
Some fixes for rank_genes_groups

### LINKED ISSUE #754: different pvals when doing wilcoxon rank_genes_groups for treatment vs. ctrl and ctrl vs. treatment
Hi,
I have two levels in my ```groupby``` variable and was trying to find the differential expression genes between the two levels using the wilcoxon rank sum test. The following two commands will give different pvals and slightly different logfoldchanges
```
sc.tl.rank_genes_groups(adata, groupby='status', groups=['ALS'], reference='ctrl', n_genes=100000, method='wilcoxon', use_raw=False)
sc.tl.rank_genes_groups(adata, groupby='status', groups=['ctrl'], reference='ALS', n_genes=100000, method='wilcoxon', use_raw=False)
```
```
	gene	logfoldchanges_ALS_ctrl	pvals_ALS_ctrl	logfoldchanges_ctrl_ALS	pvals_ctrl_ALS
0	SLC11A1	2.9489155	5.91E-75	-2.9489155	2.08E-73
1	NEAT1	1.1250153	5.11E-66	-1.1250151	6.82E-64
2	FKBP5	2.7334108	8.94E-47	-2.7334108	1.78E-45
3	SPP1	2.1242297	2.27E-42	-2.1242297	2.69E-41
4	FCGR3A	2.6661332	6.95E-40	-2.6661332	5.37E-39
5	HAMP	5.394592	1.27E-37	-5.394592	2.27E-36
6	CD163	3.0886266	9.11E-36	-3.0886264	1.71E-34
7	RASSF4	2.3211384	2.83E-34	-2.3211384	3.74E-33
8	DSE	2.8529236	7.43E-33	-2.8529236	7.86E-32
9	MAFB	2.7013724	3.67E-32	-2.7013724	6.43E-31
10	DENND3	1.4753485	5.13E-29	-1.4753484	1.19E-27
11	APOE	1.4111803	1.12E-28	-1.4111804	9.04E-28
12	C1QB	1.5169998	3.53E-27	-1.5169998	1.68E-25
13	C3	1.3675922	1.05E-25	-1.3675922	2.62E-25
```
Am I not doing it right, or because of the tie issue mentioned here?
#698 
Thanks for your help!

### PR DESCRIPTION
**Pull request by Koncopd**
Most importantly, this fixes https://github.com/theislab/scanpy/issues/754.
Also solves this problem https://github.com/theislab/scanpy/issues/753.

### CODE REVIEW

**Comment by ivirshup** [comment]
Fantastic!

Two questions:

* Was the issue from the indexing? 
* How does this compare to other implementations? Is it equivalent?

**Comment by Koncopd** [comment]
Yes, the problem was in the indexing.

Do you mean equivalent to `scipy.stats.mannwhitneyu`? No it isn't, as `scipy.stats.mannwhitneyu` doesn't support matrix inputs. Also `rank_genes_groups` doesn't support tie correction yet, but i'm going to add it.

**Comment by ivirshup** [comment]
Yeah, I was thinking `scipy.stats.mannwhitneyu` though I'm not sure if that does an approximate or exact test.

It would be good if we could match some gold standard implementation.

**Comment by Koncopd** [comment]
It is also approximate, so the comparison will be valid after i add the tie correction.

**Pull request merged**
