### PR TITLE
Update release notes for 1.7.0

### PR DESCRIPTION
**Pull request by ivirshup**
To find all PRs that have been merged since the last release: `repo:theislab/scanpy closed:>YYYY-MM-DD is:pr is:merged` where the date is the date of last release.

Boy were there a lot. There should be some automation here.

### CODE REVIEW

**Comment by flying-sheep** [comment]
Thank you! [We could try blurb](https://pypi.org/project/blurb/) for automation (if it’s not to CPython-specific)

**Comment by giovp** [comment]
I can work on #1512 tonight/tomorrow, should not be too much. Would be great to still include that in 1.7 please 🙏

**Comment by falexwolf** [comment]
Thank you, awesome! ❤️

**Comment by gokceneraslan** [comment]
Oh https://github.com/theislab/scanpy/pull/1551 would also be good to have 😅

**Pull request merged**
