### PR TITLE
Fixed inverted axis with img_key=None

### LINKED ISSUE #1059: Flipped y-axis in sc.pl.spatial without img_key
Hi. When I use `sc.pl.spatial` to visualize the same data with or without the H&E staining image in the background, the y-axis is flipped if I don't set the `img_key` parameter. Is this expected? 

```python
import scanpy as sc
from matplotlib import rcParams

adata_vis = sc.datasets.visium_sge('V1_Human_Lymph_Node')

rcParams["figure.figsize"] = [8,8]

sc.pp.calculate_qc_metrics(adata_vis, inplace=True)
sc.pl.spatial(adata_vis, img_key = "hires",color=['total_counts'])
sc.pl.spatial(adata_vis,color=['total_counts'], size=100)

```
Screenshot 2020-02-18 at 16 30 56

### PR DESCRIPTION
**Pull request by giovp**
Fixes #1059, when `img_key=None` and `basis="spatial"` y axis is flipped and plotted correctly.

### CODE REVIEW

**Comment by flying-sheep** [comment]
I think the best would be if we did this in `sc.pl.spatial`, not `sc.pl.embedding`.

**Comment by giovp** [comment]
Added a quick test

**Comment by flying-sheep** [comment]
It’s good to have one, but it should of course also make sure that the flipping works!

**Comment by giovp** [comment]
The point of making it in `sc.pl.embedding` is that if there is no image, then there is no scaling factor and it really becomes just a scatterplot. I could use another point size, but then I think it becomes yet another different behavior. Does it make sense?

**Comment by flying-sheep** [comment]
Sure, only problem is that there’s now so much spatial-specific code in `embedding`. But we can fix that after this PR.

I’d still like to see this change though:

> It’s good to have [a test], but it should of course also make sure that the flipping works!

**Comment by giovp** [comment]
Replaced by #1149

**Pull request closed without merging**
