### PR TITLE
standard_scale to plots

### PR DESCRIPTION
**Pull request by fidelram**
This PR extends the original PR #512 by @gokceneraslan which adds the `standard_scaling` parameter to matrixplot. 

I added the same functionality to dotplot, heatmap and stacked_violin.

 Also, I integrated PR #524 by @sjfleming which adds a `smallest_dot` option to dotplot.

### CODE REVIEW

**Comment by fidelram** [comment]
@falexwolf I updated the visualizations example notebook to reflect the changes: https://github.com/theislab/scanpy_usage/pull/11

**Comment by falexwolf** [comment]
Thank you! Shall we close @gokceneraslan PR then? Or do we need to merge it first and then merge this? Thanks for clarifying!

Regarding the examples: it's a bit unfortunate, but we migrated to https://github.com/theislab/scanpy-tutorials, and `scanpy_usage` is actually no longer used. I mentioned it before, but it might have got forgotten... Could you make a PR to `scanpy-tutorials` instead?

**Comment by gokceneraslan** [comment]
I think this PR has all the commits from two other PRs. Tricky to set up 😛 We can close mine.

**Comment by falexwolf** [comment]
Cool! I'll merge this then. Thanks everybody!

**Comment by fidelram** [comment]
@falexwolf  Thanks. I will add the PR to scanpy-tutorials

**Pull request merged**
