### PR TITLE
Inline example paga

### PR DESCRIPTION
**Pull request by le-ander**
adding an inline example plot for `sc.pl.paga()`
See #1664

### CODE REVIEW

**Comment by le-ander** [comment]
Hm, I am a bit lost wrt to the checks failing @giovp 
the doc build doesn't show any logs and travis fails because of black complaining about scanpy/tools/_sim.py and some version checking problem. None of this seems related to my PR 🤔

**Comment by ivirshup** [comment]
I don't think `igraph` or `louvain` are actually being installed on readthedocs. 

I think you'll need to modify the `.readthedocs.yml` for this. But not calling `louvain` could also work.

**Comment by giovp** [comment]
looks good, thanks @le-ander

**Review by giovp — APPROVED** [review]

**Comment by giovp** [comment]
I've added igraph to #1809 and seems to work, will ad it here as well

**Comment by le-ander** [comment]
Thanks a lot, giovanni!

**Pull request merged**
