### PR TITLE
Preparations for UMAP 0.4 release

### PR DESCRIPTION
**Pull request by Koncopd**
https://github.com/theislab/scanpy/issues/779

Also i see some changes in the internal nnescent of umap and it is problematic for [Ingest](https://github.com/theislab/scanpy/pull/651).

### CODE REVIEW

**Comment by gokceneraslan** [comment]
Do you think we also need to check if the umap version is >= 0.4 or so?

**Comment by flying-sheep** [comment]
Nah, if it returns a tuple, we take the first element, if not, we assume it’s a sparse matrix

**Comment by gokceneraslan** [comment]
Did anyone run scanpy tests with umap 0.4 branch?

**Comment by flying-sheep** [comment]
Not me, but I checked the current and old umap code and found that this PR will only fix things and not cause problems. IDK if umap 0.4 causes further problems

**Pull request merged**
