### PR TITLE
Fix coverage ci

### PR DESCRIPTION
**Pull request by ivirshup**
CI runs that report coverage currently don't fail if the tests fail. This is because the way the coverage job is written swallows the error. I'm updating this use the same approach as anndata, which seems to be working.

### CODE REVIEW

**Comment by flying-sheep** [comment]
Using `coverage run` is intentional. Please just configure the shell so it exits when a line fails instead of changing this.

The reason is at we have `addopts = ['-p', 'scanpy.testing.pytest']` (or so). If we use `pytest --cov`, coverage for things run during import breaks.

**Comment by ivirshup** [comment]
> coverage for things run during import breaks.

I don't really understand what you mean here. Do you have an explanation somewhere?

**Comment by flying-sheep** [comment]
This line:

https://github.com/scverse/scanpy/blob/383a61b2db0c45ba622f231f01d0e7546d99566b/pyproject.toml#L162

means that pytest imports that module together with the other plugins, and *then* runs tests.

That means that it will `import scanpy.testing._pytest` (i.e. `scanpy` and everthing imported in there) before pytest-cov is loaded and can do anything.

**Comment by ivirshup** [comment]
So, we could also not early load `scanpy.testing._pytest` or load `pytest-cov` first?

I would like to keep the `xdist` support and use a similar interface.

**Comment by flying-sheep** [comment]
This PR broke the doctest setup.

https://github.com/scverse/scanpy/pull/3057 fixes it again

**Pull request merged**
