### PR TITLE
Add tutorials images to static

### LINKED ISSUE #2132: Pictures not shown in docs
## Description

There are some pictures which are not being rendered [here](https://scanpy.readthedocs.io/en/stable/tutorials.html) in the tutorial section of the docs.

### PR DESCRIPTION
**Pull request by falexwolf**
This is a long term solution to securing the image files on the tutorials page, addressing https://github.com/theislab/scanpy/issues/2132.

### CODE REVIEW

**Review by Zethson — APPROVED** [review]
Plotting tests are flaky again.

Nothing to do with this PR.

**Comment by falexwolf** [comment]
The strange thing is that the RTD build also fails, and I don't understand how changing a few URLs and adding a few static image files can cause that. 😔

**Comment by Zethson** [comment]
```
Warning, treated as error:
/home/docs/checkouts/readthedocs.org/user_builds/icb-scanpy/checkouts/2134/scanpy/plotting/_anndata.py:docstring of scanpy.plotting._anndata.dendrogram:31:Exception occurred in plotting scanpy-pl-dendrogram-1
 from /home/docs/checkouts/readthedocs.org/user_builds/icb-scanpy/checkouts/2134/docs/generated/scanpy.pl.dendrogram.rst:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/icb-scanpy/envs/2134/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 517, in _run_code
    exec(code, ns)
  File "<string>", line 3, in <module>
  File "/home/docs/checkouts/readthedocs.org/user_builds/icb-scanpy/checkouts/2134/scanpy/tools/_dendrogram.py", line 139, in dendrogram
    corr_condensed = distance.squareform(1 - corr_matrix)
  File "/home/docs/checkouts/readthedocs.org/user_builds/icb-scanpy/envs/2134/lib/python3.8/site-packages/scipy/spatial/distance.py", line 2363, in squareform
    is_valid_dm(X, throw=True, name='X')
  File "/home/docs/checkouts/readthedocs.org/user_builds/icb-scanpy/envs/2134/lib/python3.8/site-packages/scipy/spatial/distance.py", line 2444, in is_valid_dm
    raise ValueError(('Distance matrix \'%s\' diagonal must '
ValueError: Distance matrix 'X' diagonal must be zero.
```

Some dendrogram issue. The RTD build is also flaky.

**Comment by Zethson** [comment]
But @Koncopd already has the fix @falexwolf https://github.com/theislab/scanpy/pull/2129

**Pull request merged**
