### PR TITLE
Remove pytables dependency

### PR DESCRIPTION
**Pull request by ivirshup**
Removes the need for a pytables dependency

* pytables has been a source of installation heisenbugs, particularly on windows (#1468, #1284, #454)
* why use two hdf5 libraries
* Makes it easier to move reading 10x files into anndata or elsewhere #1387

I've edited the code as lightly as possible, since these readers were originally contributed by someone at 10X, so I assume they had better knowledge of possible edge cases.

- [ ] ~~Test with h5py 2~~
- [ ] Add release note

### CODE REVIEW

**Comment by ivirshup** [comment]
I'm having trouble installing tables into a conda environment. Now may be the time to pull the trigger on this

**Comment by ivirshup** [comment]
I think I would rather just bump the h5py dependency since it's been over a year.

**Comment by Koncopd** [comment]
And what is the problem with 2.10.0 here?

**Comment by adamgayoso** [comment]
@ivirshup any reason now that pytables is gone that we can't move these functions into anndata?

**Pull request merged**
