### PR TITLE
updated read_visium() to read in spaceranger 2.0 files

### PR DESCRIPTION
**Pull request by LLehner**
Can now read in spaceranger 2.0 files where the tissue position file name is different and a header is included. Code adapated from squidpy's [read.visium()](https://github.com/scverse/squidpy/blob/main/squidpy/read/_read.py#L25) in response to [scverse/squidpy#599](https://github.com/scverse/squidpy/issues/599) and [scverse/scanpy#2296](https://github.com/scverse/scanpy/pull/2296#issuecomment-1273309536).

### CODE REVIEW

**Comment by LLehner** [comment]
10x Visium data from both space ranger 1.0.0 and 2.0.0 can be read in using ```sc.read_visium()``` and plotted using squidpy with coordinates in correct order.

space ranger 1.0.0 [data](https://www.10xgenomics.com/resources/datasets/mouse-brain-section-coronal-1-standard-1-0-0) from 10x plotted with squidpy's ```spatial_scatter()```:

spaceranger_1

space ranger 2.0.0 [data](https://www.10xgenomics.com/resources/datasets/adult-mouse-olfactory-bulb-1-standard-1) from 10x plotted with squidpy's ```spatial_scatter()```:

spaceranger_2

**Comment by LLehner** [comment]
@giovp

**Review by giovp — APPROVED** [review]

**Review by ivirshup — APPROVED** [review]
@giovp feel free to approve and merge. One request first:

Can this get a release note?

**Comment by giovp** [comment]
> @giovp feel free to approve and merge. One request first:
> 
> Can this get a release note?

for sure, @LLehner could you? think he's is on holiday until next week

**Comment by LLehner** [comment]
> for sure, @LLehner could you? think he's is on holiday until next week

sure, will do

**Review by giovp — APPROVED** [review]

**Comment by giovp** [comment]
LGTM thanks @LLehner !

**Comment by flying-sheep** [comment]
hi @LLehner, why is this `header=1`?. Doesn’t that mean “the second line of data”? Shouldn’t it be `header=0`?

**Comment by LLehner** [comment]
hi @flying-sheep, you are right. Header should be 0, otherwise the first row with values (besides the barcode) will be turned into headers and then overwritten. Didn't catch that before, since it didn't cause issues in the plotting examples.

**Comment by mortunco** [comment]
Folks. Forgive my ignorance if I am completely wrong but it seems read_visium still reads it wrong.


~https://github.com/scverse/scanpy/blob/edd613026cd5991baf92c8308b5ee2375089adc8/scanpy/readwrite.py#L466C1-L473~


another edit:
https://github.com/scverse/scanpy/blob/89804c26bcbdde4449dfe98b3193a9d28c2a0e2f/scanpy/readwrite.py#L466-L482

Basically line 476 is fixes the switch and makes the barcode coordinates in (x,y).

I apologise for the confusion.

**Comment by grst** [comment]
With https://github.com/scverse/spatialdata-io/pull/102 we could consider replacing `scanpy.read_visium` with

```python
def read_visium(*args, **kwargs): 
    import spatialdata_io
    return spatialdata_io.visium(*args, **kwargs).to_legacy_anndata()
```

and avoid maintaing the annoying spaceranger output parsing in multiple locations.

**Pull request merged**
