### PR TITLE
A few minor style changes via `pyupgrade`

### PR DESCRIPTION
**Pull request by chris-rands**
I ran:
```
pyupgrade --keep-percent-format --py3-plus scanpy/*py scanpy/*/*py scanpy/*/*/*py
```

### CODE REVIEW

**Comment by chris-rands** [comment]
I guess there is no interest to merge this so I close it now (it's probably easier to re-run `pyupgrade` than deal with the conflicts anyway)

**Comment by flying-sheep** [comment]
You sure? Let me try!

**Comment by flying-sheep** [comment]
Thank you! Sorry for missing this.

**Comment by chris-rands** [comment]
Thank you for resolving the conflict and merging!

**Pull request merged**
