### PR TITLE
Sphinx 4.1 fixes

### LINKED ISSUE #1946: Sphinx 4.1.0 doesn't like ScanpyConfig
Update:

Docs don't build with sphinx 4.1.0 due to a error triggered by `scanpydoc`. Sphinx will be pinned until this is solved (which is when this issue should be closed). It's not obvious to me at the moment whether sphinx or scanpydoc is at fault.

---------------

Trying to build the docs with Sphinx 4.1.0 fails with the following output:

<details>
<summary> </summary>

```sh
$ make html
Running Sphinx v4.1.0
loading intersphinx inventory from https://anndata.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://bbknn.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://matplotlib.org/cycler/objects.inv...
loading intersphinx inventory from http://docs.h5py.org/en/stable/objects.inv...
loading intersphinx inventory from https://ipython.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://leidenalg.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://louvain-igraph.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://matplotlib.org/objects.inv...
loading intersphinx inventory from https://networkx.github.io/documentation/networkx-1.10/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/numpy/objects.inv...
loading intersphinx inventory from https://pandas.pydata.org/pandas-docs/stable/objects.inv...
loading intersphinx inventory from https://docs.pytest.org/en/latest/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/scipy/reference/objects.inv...
loading intersphinx inventory from https://seaborn.pydata.org/objects.inv...
loading intersphinx inventory from https://scikit-learn.org/stable/objects.inv...
loading intersphinx inventory from https://scanpy-tutorials.readthedocs.io/en/latest/objects.inv...
intersphinx inventory has moved: https://networkx.github.io/documentation/networkx-1.10/objects.inv -> https://networkx.org/documentation/networkx-1.10/objects.inv
intersphinx inventory has moved: https://docs.scipy.org/doc/numpy/objects.inv -> https://numpy.org/doc/stable/objects.inv
intersphinx inventory has moved: http://docs.h5py.org/en/stable/objects.inv -> https://docs.h5py.org/en/stable/objects.inv
[autosummary] generating autosummary for: _key_contributors.rst, api.rst, basic_usage.rst, community.rst, contributors.rst, dev/ci.rst, dev/code.rst, dev/documentation.rst, dev/external-tools.rst, dev/getting-set-up.rst, ..., release-notes/1.7.1.rst, release-notes/1.7.2.rst, release-notes/1.8.0.rst, release-notes/1.8.1.rst, release-notes/1.8.2.rst, release-notes/1.9.0.rst, release-notes/index.rst, release-notes/release-latest.rst, tutorials.rst, usage-principles.rst
Error in github_url('scanpy._settings.ScanpyConfig.N_PCS'):

Extension error (sphinx.ext.autosummary):
Handler <function process_generate_options at 0x139c4a940> for event 'builder-inited' threw an exception (exception: type object 'ScanpyConfig' has no attribute 'N_PCS')
make: *** [html] Error 2
```

</details>

However, I'm entirely sure if this is Sphinx's fault, or our own. Currently the [N_PCS parameter isn't in the rendered documentation](https://scanpy.readthedocs.io/en/stable/generated/scanpy._settings.ScanpyConfig.html#scanpy._settings.ScanpyConfig). I think it should be, and am not sure why it's not showing up here.

To summarize:

* Previous versions of our doc builds didn't seem to be including attribute docstrings for `ScanpyConfig`.
* Sphinx 4.1.0 raises an error when it hits this attribute

### PR DESCRIPTION
**Pull request by flying-sheep**
Fixes #1946

### CODE REVIEW

**Comment by ivirshup** [comment]
Do you expect this to be compatible with older sphinx versions?

------

Re your comment here: https://github.com/theislab/scanpy/issues/1946#issuecomment-879060220

I can replicate this warning locally with multiple uses of scipy sparse, as well as `AnnData`.

```
/Users/isaac/github/scanpy/scanpy/metrics/_gearys_c.py:docstring of scanpy.metrics._gearys_c.gearys_c:: WARNING: py:class reference target not found: scipy.sparse.csr.csr_matrix
/Users/isaac/github/scanpy/scanpy/metrics/_morans_i.py:docstring of scanpy.metrics._morans_i.morans_i:: WARNING: py:class reference target not found: scipy.sparse.csr.csr_matrix
/Users/isaac/github/scanpy/scanpy/preprocessing/_simple.py:docstring of scanpy.preprocessing._simple.log1p:: WARNING: py:class reference target not found: scipy.sparse.base.spmatrix
/Users/isaac/github/scanpy/scanpy/preprocessing/_simple.py:docstring of scanpy.preprocessing._simple.log1p:: WARNING: py:class reference target not found: anndata._core.anndata.AnnData
/Users/isaac/github/scanpy/scanpy/preprocessing/_simple.py:docstring of scanpy.preprocessing._simple.log1p:: WARNING: py:class reference target not found: anndata._core.anndata.AnnData
/Users/isaac/github/scanpy/scanpy/preprocessing/_simple.py:docstring of scanpy.preprocessing._simple.scale:: WARNING: py:class reference target not found: scipy.sparse.base.spmatrix
```

I can't replicate with `Sphinx<4.1`, so I suspect it's upstream. Not sure if this could be something on our end, though I recall having issues with "fully resolved" names before.

**Comment by ivirshup** [comment]
I think the new problem (with references to qualified names not being found) may be related to `qualname_overrides` and this issue: https://github.com/sphinx-doc/sphinx/issues/9395

**Comment by flying-sheep** [comment]
> Do you expect this to be compatible with older sphinx versions?

Of course! Why would it not be?

> I think the new problem […] may be related to `qualname_overrides`

Hmm, sphinx-doc/sphinx#9026 should make `qualname_overrides` unnecessary for classes if the referenced docs have been built with a sphinx version containing that PR (4.1 or later).

Maybe we can link to the `dev` docs? https://scipy.github.io/devdocs/reference/

**Comment by flying-sheep** [comment]
Hahah! @ivirshup what do you think?

**Comment by ivirshup** [comment]
So the issue is incompatibilities between versions of sphinx and their `objects.inv`? Is there an open issue in sphinx for this?

> > Do you expect this to be compatible with older sphinx versions?
>
> Of course! Why would it not be?

Mostly because the inner workings of Sphinx are a mystery to me, so I have no idea what features your changes rely on 😆

This was mainly me asking if we should bump the minimum version of sphinx allowed. Maybe we should if there are issues with the `objects.inv`s?

> Maybe we can link to the dev docs?

Or we could add the classes to nitpick ignore? Then once the docs are rebuilt it will do the right thing without any intervention, and we don't have to be keeping an eye out for this. My main concern here is that the `scipy.github.io` address may not be permanent, similar to how numpy temporarily used a github.io address while they revamped their docs. Basically, it may just break or go down without notice.

I thought we could even just trigger a new build of the anndata stable docs, but there's an issue there, probably to do with sphinx not being pinned on release. I do want to make a new anndata release soon-ish though.

-----------

I'm happy for you to pick one of the approaches and merge it. AnnData could also use a fix for this, I've temporarily just pinned sphinx below 4.1 there too.

**Comment by flying-sheep** [comment]
> So the issue is incompatibilities between versions of sphinx and their `objects.inv`? Is there an open issue in sphinx for this?

IDK, what I meant is that sphinx 4.1 creates a `objects.inv` which allows to reference classes by their internal location like `f'{cls.__module__}.{cls.__qualname__}'`. Therefore pointing to an `objects.inv` build using 4.1+ from 4.1+ makes `qualname_overrides` superfluous.

So if we want to guarantee that all links resolve no matter who builds the docs, we should just require 4.1+. If we just want our docs to build, we can leave things as they are.

I think the next scipy version will take a while to arrive, so I think anndata stable + adding scipy to nitpick_ignore might be best.

Aaand it works!

**Pull request merged**
