### PR TITLE
fix ingest for umap 0.5

### PR DESCRIPTION
**Pull request by Koncopd**
subj
https://github.com/theislab/scanpy/issues/1509
`rp_forest` storage is still broken though.

### CODE REVIEW

**Comment by ivirshup** [comment]
Would making pynndescent a requirement make the code here a bit more simple? I'm wondering if all the branches around umap versions and whether pynndescent is present could be removed.

**Comment by Koncopd** [comment]
For umap 0.5 pynndescent is in requirements, so it is used here also. For backwards compatibility i left the code for the old versions. I think i will remove the old code sometime in the future and just use pynndescent and umap >= 0.5.

**Comment by ivirshup** [comment]
> rp_forest storage is still broken though.

Is this something you are planning on fixing in this pr?

Also, what's broken about it? I would have thought we'd have a failing test.

**Comment by Koncopd** [comment]
I am checking, it seems that the format for `rp_forest `changed significantly.

No, failing forest conversion won't cause any problems because it was deliberately coded to avoid problems. The code is in neighbors, and neighbors is critical functuionality and can work without `rp_forest`.

**Comment by ivirshup** [comment]
> I am checking, it seems that the format for rp_forest changed significantly

Can we validate the format? If so, can we just recalculate the forest if the format isn't what we expect?

Also, can you point me to the code where this is handled in `ingest`? I feel like something user visible should happen if there's malformed data in the object.

**Comment by Koncopd** [comment]
https://github.com/theislab/scanpy/blob/5fc12f4a918e21f0c57937b787d52040db046f01/scanpy/neighbors/__init__.py#L284
https://github.com/theislab/scanpy/blob/5fc12f4a918e21f0c57937b787d52040db046f01/scanpy/neighbors/__init__.py#L436
https://github.com/theislab/scanpy/blob/5fc12f4a918e21f0c57937b787d52040db046f01/scanpy/neighbors/__init__.py#L177
https://github.com/theislab/scanpy/blob/5fc12f4a918e21f0c57937b787d52040db046f01/scanpy/neighbors/__init__.py#L736

`rp_forest` is handled in neighbors.

**Comment by ivirshup** [comment]
Alright, I was more wondering how you were handling the forest right now, but I see that you're just calculating it. I suspect there will be a minimum version bound needed for the `init_graph` parameter.

Let me know when you think this is ready to merge.

**Comment by Koncopd** [comment]
@ivirshup i am merging this and will work on `rp_forest` later.

**Comment by ivirshup** [comment]
@Meeseeksdev backport to 1.7.x

**Pull request merged**
