### PR TITLE
improvements on plotting functions that use 'groupby'

### PR DESCRIPTION
**Pull request by fidelram**
This PR addresses issues from #979 and #1103 related to `sc.pl.dotplot` and replaces PR #1127

Furthermore, the current PR attempts to unify common code between `dotplot`, `matrixplot` and `stacked_violin` plots while at the same time adding more flexibility to the plots. 

This PR also makes possible to plot fold changes, log fold changes and p-values from `sc.tl.rank_genes_groups` as suggested in #562

To achieve this the `sc.pl.dotplot`, `sc.pl.matrixplot` and `sc.pl.stacked_violin` method had been transformed into wrappers for the new `DotPlot`, `MatrixPlot` and `StackedVioling` classes. Accessing the new classes directly allows further fine tuning of the plots.

The use of the `sc.pl.dotplot`, `sc.pl.matrixplot` and `sc.pl.stacked_violin`  didn't change, only the new parameter `return_fig` was added.

For clarity, the relevant code has been moved to `scanpy.plotting._groupby_plots.py`. 

The new plot classes are all descendants of a `BasePlot` class that captures most of the common code shared between the plots. The design of the classes follows the method chaining (as found in Pandas or Altair). This allows the addition of independent features (via well documented methods) to the plot without increasing the number parameters of a single function. This was first suggested here #956. 

For example, for dotplot is now is possible to `add category totals`, define the titles for the colorbar and size legend and modify the values for edge color and edge line with for dot plot and the size exponent used (among may other options). For example:

```PYTHON
adata = sc.datasets.pbmc68k_reduced()
markers = {'T-cell': ['CD3D', 'CD3E', 'IL32'], 'B-cell': ['CD79A', 'CD79B', 'MS4A1'], 
           'myeloid': ['CST3', 'LYZ']}
dp = sc.pl.dotplot(adata, markers, groupby='bulk_labels', return_fig=True)
dp.add_totals(size=1.2)\
    .legend(color_title='log(UMI count+1)', width=1.6, show_size_legend=True)\
    .style(cmap='Blues', dot_edge_color='black', dot_edge_lw=1, size_exponent=1.5)\
    .show()
```
All objects have consistent functions for `legend`, to set up titles and width, `style()` to set visual parameters specific to each plot like colormap, edge color, linewidth. `swap_axes` to transpose the figure, `add_dendrogram` with options to change the with of the dendrogran and `add_total` tho show a bar plot of the total number of cells per category. Also includes options to sort the categories.

image

Here is description of changes:
**all figures**:
 * Set a title to the image. 
 * Pass an `axe` where to plot the image.
 * Return a dictionary of axes for further manipulation
 * using `return_fig` the plot object can be used to adjust the proportions to the legend and other visual aspects can be fine tuned.
 * a bar plot with the totals per category can be added. This will align at the left of the image if the categories are plotted in rows or at the top if they are plotted in columns.
 * legend can be removed
 * `groupby` can be a list of categories. 

**dotplot**
 * Improved the colorbar and size legend for dotplots. Now the colorbar and size have titles, which can be modified using the `colorbar_title` and `size_title` arguments. They also align at the bottom of the image and do not shrink if the dotplot image is smaller.
 * Plot genes in rows and categories in columns (swap_axes).
 * Using the DotPlot object the dot_edge_color and line width can be set up, a grid added as well as several other features
 * `sc.pl.rank_genes_groups_dotplot` can now plot `pvals` and `log fold changes`

**matrixplot**
 * added title for colorbar and positioned as in dotplot
 * `sc.pl.rank_genes_groups_matrixplot` can now plot `pvals` and `log fold changes`

**stacked_violin**
 * [update] violin colors can be colored based on average gene expression as in dotplots
 * made the linewidth of the violin plots smaller.
 * removed the tics for the y axis as they tend to overlap with each other. Using the `style` method they can be visualized.

TODO:
 - [x] Update tests
 - [x] Update tutorial and readthedocs

### CODE REVIEW

**Comment by z5ouyang** [comment]
This looks nice.
Any estimation of this will be merged into master? Thanks

**Comment by fidelram** [comment]
@z5ouyang Mostly is ready. I have been using it and does not break any previous functionality. Seems quite stable. I am now working on the tutorial.

**Comment by fidelram** [comment]
@ivirshup @flying-sheep @falexwolf 

I would like to merge this branch soon and I would like your opinion on the following:
 * Extended functionality and fine tuning of the plots is achieved by using the new plot objects. However, I don't know how they can be documented in readthedocs (or if we want that). Note: the object methods are well documented and can be accessed, for example in Jupyter notebooks.

 * I am using `return_fig` as an argument to return the plot object in `sc.pl.dotplot` etc. Is this a good name choice?

As mentioned previously, the current PR tries to keep the current functionality with minimal changes to the way functions like `sc.pl.dotplot` are called. On the background, the code was refactored to remove much repetition as possible and allow new functionally. 

The current progress on the visualization tutorial is here: https://nbviewer.jupyter.org/github/fidelram/scanpy-tutorials/blob/marker_genes_vis_tutorial/visualizing-marker-genes.ipynb

**Comment by fidelram** [comment]
The last changes in `stacked_violin` allows to use a color map as in `dotplot`

```PYTHON
pmbc = sc.datasets.pbmc68k_reduced()
marker_genes_dict = {'NK': ['GNLY', 'NKG7'], 'T-cell': ['CD3D'], 
                     'B-cell': ['CD79A', 'MS4A1'],
                     'Monocytes': ['FCGR3A'],
                     'Dendritic': ['FCER1A']}

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11,5), gridspec_kw={'wspace':0.3})
sc.pl.stacked_violin(pbmc, marker_genes_dict, groupby='bulk_labels', ax=ax1, show=False)
sc.pl.dotplot(pbmc, marker_genes_dict, groupby='bulk_labels', ax=ax2, show=False)
``` 

image

**Comment by gokceneraslan** [comment]
In the dotplots, when the color_on == 'square', fixed dot edge color might lead to some trouble in visibility when the square color and dot edge color happen to be similar.

There is a nice feature of seaborn heatmap to avoid exactly that, where the annotation text color is determined conditionally on the square color, see [here](https://seaborn.pydata.org/generated/seaborn.heatmap.html) for the documentation and [here](https://github.com/mwaskom/seaborn/blob/master/seaborn/matrix.py#L261) for the relevant code:

image

It can be too much work, feel free to ignore but just wanted to highlight.

**Comment by fidelram** [comment]
@gokceneraslan Thanks for pointing this out! The `relative_luminance` function required for this can be easily imported from seaborn, therefore, I imagine that the code can be adapted easily.

**Comment by fidelram** [comment]
@gokceneraslan I just added the dynamic coloring of the circles when the color is on the background square. 

```PYTHON
adata = sc.datasets.pbmc68k_reduced()
markers = {'T-cell': ['CD3D', 'CD3E', 'IL32'], 
           'B-cell': ['CD79A', 'CD79B', 'MS4A1'],
           'myeloid': ['CST3', 'LYZ']}

sc.pl.dotplot(adata, markers, groupby='bulk_labels', return_fig=True)\
             .style(color_on='square', cmap='binary').show()
```

image

**Comment by gokceneraslan** [comment]
Looks phenomenal! Thanks so much.

**Comment by ivirshup** [comment]
@fidelram Sorry, I completely missed your asking for a review! It does look good though.

However, it looks like this is breaking the docs. Could you take a look into that?

**Comment by ivirshup** [comment]
I think the issue that there are references to the `DotPlot` class, but no doc page get's generated for that class. I think this can be fixed by adding something like:

```rst
Classes used for these plots:

.. autosummary::
   :toctree: .

   pl._dotplot.DotPlot
```

to the doc-string of the plotting module.

Once this exists, there might be some other errors that pop up.

**Comment by gokceneraslan** [comment]
> @gokceneraslan I just added the dynamic coloring of the circles when the color is on the background square.

@fidelram The cool dynamic line coloring feature seems broken now, I wonder why :/

image

**Comment by fidelram** [comment]
Is because we changed dot edge the defaults shortly before the release. Time to add a test for this.

I will make a fix but meanwhile you can trigger the dynamic coloring by setting `dot_edge_color` and `dot_edge_lw` as `None`:

```PYTHON
sc.pl.dotplot(adata, markers, groupby='bulk_labels', return_fig=True)\
             .style(color_on='square',  dot_edge_color=None, dot_edge_lw=None).show()
```

**Comment by flying-sheep** [comment]
I wonder why the default for `size_exponent` is 1.5 …

Unless there’s a bias in human perception that suggests this, I’d say only a value of 2.0 makes sense (meaning area corresponds to value)

**Pull request merged**
