### PR TITLE
Add bento to ecosystem

### PR DESCRIPTION
**Pull request by ckmah**
I would like to add `bento` to the Ecosystems page, a toolkit I have developed for subcellular spatial transcriptomics analysis. Please let me know if I need to add anything else. Thanks!

### CODE REVIEW

**Comment by Zethson** [comment]
@ckmah we'll have a new way of highlighting community and ecosystem work within scverse soon. This list might get deprecated then.

**Comment by Zethson** [comment]
Slightly unrelated feedback: I think that your API documentation is broken or incomplete: https://bento-tools.readthedocs.io/en/latest/api.html#tools

Would be great to have it complete so that people can use your tool easily.

**Comment by ivirshup** [comment]
I'm just going to merge this for now, though we might just point to https://scverse.org/packages/#ecosystem in the future

**Comment by ivirshup** [comment]
Thanks @ckmah!

**Pull request merged**
