### PR TITLE
Add issues topic to contributing guidelines

### PR DESCRIPTION
**Pull request by ivirshup**
Saw a couple duplicate issues and figured updating the contributing guidelines could help with that. Anything I forgot to mention?

### CODE REVIEW

**Comment by flying-sheep** [comment]
Looks good! Additionally we should also add some issue templates (maybe one for bugs and one for feature requests)

(But that ofc doesn’t have to be in this PR)

**Comment by falexwolf** [comment]
Thank you, great! :)

**Comment by ivirshup** [comment]
@flying-sheep, while I like the idea of issue templates in theory, I often find them patronizing in practice. Do you have examples of ones that you've liked?

**Comment by flying-sheep** [comment]
The ones from vscode are pretty good: https://github.com/Microsoft/vscode/issues/new/choose

**Comment by ivirshup** [comment]
Those are good! Short and simple.

**Pull request merged**
