### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by ivirshup**
Some links have been broken in the index page

### CODE REVIEW

**Review by flying-sheep — CHANGES_REQUESTED** [review]
That’s the opposite of what I asked for

**Comment by ivirshup** [comment]
These are all one off links that are currently broken in the build and have to be compatible with github markdown since it's in the repo readme, so inter-sphinx is not an option.

**Comment by flying-sheep** [comment]
Because they’re supposed to look like this: https://spec.commonmark.org/0.30/#collapsed-reference-link

Please fix them by using standard markdown instead of making them inline.

**Comment by flying-sheep** [comment]
This should do the trick, without relying on something as fragile as line numbers.

Unless MyST somehow breaks include by converting things to rST before executing the include directive or something silly like that.

/edit: hahaha of course it does:

```
/home/docs/checkouts/readthedocs.org/user_builds/icb-scanpy/checkouts/2953/docs/index.md:1: WARNING: 'include': Invalid option value for 'end-before': None: argument required but none supplied [myst.directive_parse]
```

why? how?

**Review by flying-sheep — APPROVED** [review]

**Pull request merged**
