### PR TITLE
Phenograph clustering

### PR DESCRIPTION
**Pull request by awnimo**
Hi @falexwolf 

Added a small wrapper for phenograph clustering, similar to phate.

### CODE REVIEW

**Comment by falexwolf** [comment]
Thank you! Can you adapt the doc string so that it matches the other tools. We need numpydoc style documentation for it to render properly. You can also check whether it looks good by running `make html` in the docs folder.

**Comment by awnimo** [comment]
All done! docstring corrected to render properly!

Thank you...

**Comment by falexwolf** [comment]
Sorry about this taking so long, I'm waiting until we have the new way of handling extensions in place... It will only be another couple of days and then this is going to be merged and adapted to that... There's nothing to do from your end on this... Thank you!

**Comment by flying-sheep** [comment]
@falexwolf what is that new way? isn’t there a tracking issue where extensions should be discussed and you said we don’t need them at all?

**Comment by falexwolf** [comment]
I simply meant to do what I described in that issue:  https://github.com/theislab/scanpy/issues/271#issuecomment-431634492

**Comment by falexwolf** [comment]
I'm finally merging this as we know have the `scanpy.external` submodule, where this can be properly linked - along with PHATE and all other wrappers to external single-cell packages.

Sorry for that this took so long, I only could do this during the past calm couple of days. Thank you for the PR!

A very happy new year to you!

**Pull request merged**
