### PR TITLE
Sort obs_indices during subsample

### LINKED ISSUE #18: Error: "invalid class `dgRMatrix` object"
Hi Phil,

I'm just updating my case study notebook and updated `anndata2ri` for that. However, when converting my anndata object via:

```r
%%R -i adata_ent
print('test')
```

 I get the following error:

```pytb
---------------------------------------------------------------------------
RRuntimeError                             Traceback (most recent call last)
<ipython-input-81-f8bea5081b84> in <module>
----> 1 get_ipython().run_cell_magic('R', '-i adata_ent', "print('test')\n")

~/anaconda3/envs/sc-tutorial/lib/python3.6/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2321             magic_arg_s = self.var_expand(line, stack_depth)
   2322             with self.builtin_trap:
-> 2323                 result = fn(magic_arg_s, cell)
   2324             return result
   2325 

<decorator-gen-797> in R(self, line, cell, local_ns)

~/anaconda3/envs/sc-tutorial/lib/python3.6/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/anaconda3/envs/sc-tutorial/lib/python3.6/site-packages/rpy2/ipython/rmagic.py in R(self, line, cell, local_ns)
    704                         raise NameError("name '%s' is not defined" % input)
    705                 with localconverter(converter) as cv:
--> 706                     ro.r.assign(input, val)
    707 
    708         tmpd = self.setup_graphics(args)

~/anaconda3/envs/sc-tutorial/lib/python3.6/site-packages/rpy2/robjects/functions.py in __call__(self, *args, **kwargs)
    190                 kwargs[r_k] = v
    191         return (super(SignatureTranslatedFunction, self)
--> 192                 .__call__(*args, **kwargs))
    193 
    194 

~/anaconda3/envs/sc-tutorial/lib/python3.6/site-packages/rpy2/robjects/functions.py in __call__(self, *args, **kwargs)
    111 
    112     def __call__(self, *args, **kwargs):
--> 113         new_args = [conversion.py2rpy(a) for a in args]
    114         new_kwargs = {}
    115         for k, v in kwargs.items():

~/anaconda3/envs/sc-tutorial/lib/python3.6/site-packages/rpy2/robjects/functions.py in <listcomp>(.0)
    111 
    112     def __call__(self, *args, **kwargs):
--> 113         new_args = [conversion.py2rpy(a) for a in args]
    114         new_kwargs = {}
    115         for k, v in kwargs.items():

~/anaconda3/envs/sc-tutorial/lib/python3.6/functools.py in wrapper(*args, **kw)
    805                             '1 positional argument')
    806 
--> 807         return dispatch(args[0].__class__)(*args, **kw)
    808 
    809     funcname = getattr(func, '__name__', 'singledispatch function')

~/anaconda3/envs/sc-tutorial/lib/python3.6/site-packages/anndata2ri/py2r.py in py2rpy_anndata(obj)
     69         # Convert everything we know
     70         with localconverter(full_converter() + dict_converter):
---> 71             metadata = ListVector(obj.uns.items())
     72 
     73         rd_args = {conv_name.scanpy2sce(k): mat_converter.py2rpy(obj.obsm[k]) for k in obj.obsm.keys()}

~/anaconda3/envs/sc-tutorial/lib/python3.6/site-packages/rpy2/robjects/vectors.py in __init__(self, tlist)
    628                 raise ValueError('tlist should have a /method/ __iter__ '
    629                                  '(not an attribute)')
--> 630             kv = [(str(k), conversion.py2rpy(v)) for k, v in tlist]
    631             kv = tuple(kv)
    632             df = baseenv_ri.find("list").rcall(kv, globalenv_ri)

~/anaconda3/envs/sc-tutorial/lib/python3.6/site-packages/rpy2/robjects/vectors.py in <listcomp>(.0)
    628                 raise ValueError('tlist should have a /method/ __iter__ '
    629                                  '(not an attribute)')
--> 630             kv = [(str(k), conversion.py2rpy(v)) for k, v in tlist]
    631             kv = tuple(kv)
    632             df = baseenv_ri.find("list").rcall(kv, globalenv_ri)

~/anaconda3/envs/sc-tutorial/lib/python3.6/functools.py in wrapper(*args, **kw)
    805                             '1 positional argument')
    806 
--> 807         return dispatch(args[0].__class__)(*args, **kw)
    808 
    809     funcname = getattr(func, '__name__', 'singledispatch function')

~/anaconda3/envs/sc-tutorial/lib/python3.6/site-packages/anndata2ri/py2r.py in py2rpy_dict(obj)
     33     for k, v in obj.items():
     34         try:
---> 35             converted[str(k)] = conversion.py2rpy(v)
     36         except NotImplementedError as e:
     37             warn(str(e), NotConvertedWarning)

~/anaconda3/envs/sc-tutorial/lib/python3.6/functools.py in wrapper(*args, **kw)
    805                             '1 positional argument')
    806 
--> 807         return dispatch(args[0].__class__)(*args, **kw)
    808 
    809     funcname = getattr(func, '__name__', 'singledispatch function')

~/anaconda3/envs/sc-tutorial/lib/python3.6/site-packages/anndata2ri/scipy2ri/py2r.py in wrapper(obj)
     40 
     41         with localconverter(default_converter + numpy2ri.converter):
---> 42             return f(obj)
     43 
     44     return wrapper

~/anaconda3/envs/sc-tutorial/lib/python3.6/site-packages/anndata2ri/scipy2ri/py2r.py in csr_to_rmat(csr)
     67         p=as_integer(csr.indptr),
     68         x=conv_data(csr.data),
---> 69         Dim=as_integer(list(csr.shape)),
     70     )
     71 

~/anaconda3/envs/sc-tutorial/lib/python3.6/site-packages/rpy2/robjects/functions.py in __call__(self, *args, **kwargs)
    190                 kwargs[r_k] = v
    191         return (super(SignatureTranslatedFunction, self)
--> 192                 .__call__(*args, **kwargs))
    193 
    194 

~/anaconda3/envs/sc-tutorial/lib/python3.6/site-packages/rpy2/robjects/functions.py in __call__(self, *args, **kwargs)
    119             else:
    120                 new_kwargs[k] = conversion.py2rpy(v)
--> 121         res = super(Function, self).__call__(*new_args, **new_kwargs)
    122         res = conversion.rpy2py(res)
    123         return res

~/anaconda3/envs/sc-tutorial/lib/python3.6/site-packages/rpy2/rinterface_lib/conversion.py in _(*args, **kwargs)
     26 def _cdata_res_to_rinterface(function):
     27     def _(*args, **kwargs):
---> 28         cdata = function(*args, **kwargs)
     29         # TODO: test cdata is of the expected CType
     30         return _cdata_to_rinterface(cdata)

~/anaconda3/envs/sc-tutorial/lib/python3.6/site-packages/rpy2/rinterface.py in __call__(self, *args, **kwargs)
    771                     error_occured))
    772             if error_occured[0]:
--> 773                 raise embedded.RRuntimeError(_rinterface._geterrmessage())
    774         return res
    775 

RRuntimeError: Error in validObject(.Object) : 
  invalid class “dgRMatrix” object: slot j is not increasing inside a column
Calls: <Anonymous> ... initialize -> callNextMethod -> .nextMethod -> validObject
```

I'm pretty sure this has to do with versions in my conda environment as anndata2ri conversion worked fine when I worked locally on my laptop. Any idea if there are any R version dependencies that might not be met?

### PR DESCRIPTION
**Pull request by dburkhardt**
Fixes https://github.com/theislab/anndata2ri/issues/18

### CODE REVIEW

**Comment by dburkhardt** [comment]
Currently there's an error being raised because the following images in don't match

path: `scanpy/tests/notebooks/_images_paga_paul15_subsampled/paga_path.png`

**Expected**
paga_path

**Actual**
paga_path

**Diff**
paga_path-failed-diff

I'm going to update expected to match actual, but I need some help to see if this is okay

**Comment by ivirshup** [comment]
It looks like the issue was fixed in anndata2ri. Do you want to proceed with this PR?

**Comment by dburkhardt** [comment]
Up to you all. I think it's neater to have the output returned in the same order as the input array. The only concern would be the overhead of sorting, but that should be minimal even for large arrays never mind the expectation that we should only be choosing a small number of cells given the intended use of the function.

**Comment by ivirshup** [comment]
For me, if I'm sampling from my data I probably don't want to preserve any effects from the ordering. There are cases where this might be useful, but it's less frequent. I don't think it's common enough to change the default.

I could be convinced about this behavior being turned on with a keyword argument.

IIRC @gokceneraslan was thinking about this function. Any opinion?

**Comment by gokceneraslan** [comment]
I'm fine either way 😊

**Comment by dburkhardt** [comment]
I just added a shuffle option (off by default). I don't think it matters very much, but if you have an algorithm that is sensitive to the order of the input, I don't think you should be relying on the subsample function to shuffle your data. I'd rather encourage people to explicitly shuffle their data if that's necessary (like for plotting a scatterplot)

**Comment by ivirshup** [comment]
I think I'd like to leave this as it, and have shuffling/ ordering be an orthogonal step.

**Pull request closed without merging**
