### PR TITLE
Add neighbors_key to paga

### PR DESCRIPTION
**Pull request by Koncopd**
And changes to neighbors return section of the docstring.

### CODE REVIEW

**Comment by Koncopd** [comment]
@ivirshup @flying-sheep 
Hi, do you know how to find out why `docs/readthedocs.com` fails?

**Comment by ivirshup** [comment]
Not sure. Do the docs build fine for you locally?

**Comment by Koncopd** [comment]
@ivirshup yes, they build fine but there are a lot of warnings of the form `"WARNING: py:class reference target not found: scanpy._compat.Literal_"`.

**Comment by Koncopd** [comment]
Ok, seems like the problem was on the side of readthedocs.com.

**Pull request merged**
