### PR TITLE
Alexmascension ecosystem

### PR DESCRIPTION
**Pull request by alexmascension**

### CODE REVIEW

**Comment by ivirshup** [comment]
Thanks for the PR!

On content, I think it would be helpful if this had a short description of the method. Also, what you like it to say in the release notes?

I've changed the base from `1.7.x` to `master` since it looks like you've added the commit on the `master` branch. I think it makes the most sense to add this to the master branch for now, and I'll get back to you on whether the docs will be updated with the `1.7.2` or the `1.8.0`  release.

**Comment by ivirshup** [comment]
Thanks for the addition!

**Comment by alexmascension** [comment]
Hi! Thanks for the addition. In the release notes I guess something like "Triku, a new feature selection method was added to our ecosystem" would be fine. 

As for committing to the master, sorry for that. I am eager to see it in the 1.8.0 release!

**Comment by ivirshup** [comment]
No problem! 

Also, this will go into the 1.7.2 release, but all changes should be made to master while only some get back ported to the current release branch.

**Comment by ivirshup** [comment]
@meeseeksdev backport to 1.7.x

**Pull request merged**
