### PR TITLE
Fix rank_genes_groups_violin when use_raw=False

### LINKED ISSUE #1199: Exception: Data must be 1-dimensional from sc.pl.rank_genes_groups_violin
I was using the sc.pl.rank_genes_groups_violinfunction and got the error:

```
Exception                                 Traceback (most recent call last)
<ipython-input-195-8f87448845a3> in <module>
      1 sc.tl.rank_genes_groups(adata, 'leiden', groups=['0'], reference='1', method='wilcoxon')
----> 2 sc.pl.rank_genes_groups_violin(adata, groups='0', n_genes=1)

~/miniconda3/envs/scrna/lib/python3.7/site-packages/scanpy/plotting/_tools/__init__.py in rank_genes_groups_violin(adata, groups, n_genes, gene_names, gene_symbols, use_raw, key, split, scale, strip, jitter, size, ax, show, save)
    727             if issparse(X_col): X_col = X_col.toarray().flatten()
    728             new_gene_names.append(g)
--> 729             df[g] = X_col
    730         df['hue'] = adata.obs[groups_key].astype(str).values
    731         if reference == 'rest':

~/miniconda3/envs/scrna/lib/python3.7/site-packages/pandas/core/frame.py in __setitem__(self, key, value)
   2936         else:
   2937             # set column
-> 2938             self._set_item(key, value)
   2939 
   2940     def _setitem_slice(self, key, value):

~/miniconda3/envs/scrna/lib/python3.7/site-packages/pandas/core/frame.py in _set_item(self, key, value)
   2997         """
   2998 
-> 2999         self._ensure_valid_index(value)
   3000         value = self._sanitize_column(key, value)
   3001         NDFrame._set_item(self, key, value)

~/miniconda3/envs/scrna/lib/python3.7/site-packages/pandas/core/frame.py in _ensure_valid_index(self, value)
   3052         if not len(self.index) and is_list_like(value) and len(value):
   3053             try:
-> 3054                 value = Series(value)
   3055             except (ValueError, NotImplementedError, TypeError):
   3056                 raise ValueError(

~/miniconda3/envs/scrna/lib/python3.7/site-packages/pandas/core/series.py in __init__(self, data, index, dtype, name, copy, fastpath)
    303                     data = data.copy()
    304             else:
--> 305                 data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
    306 
    307                 data = SingleBlockManager(data, index, fastpath=True)

~/miniconda3/envs/scrna/lib/python3.7/site-packages/pandas/core/construction.py in sanitize_array(data, index, dtype, copy, raise_cast_failure)
    480     elif subarr.ndim > 1:
    481         if isinstance(data, np.ndarray):
--> 482             raise Exception("Data must be 1-dimensional")
    483         else:
    484             subarr = com.asarray_tuplesafe(data, dtype=dtype)

Exception: Data must be 1-dimensional
```

```python
...
```

```pytb
...
```

#### Versions:

> scanpy==1.4.6 anndata==0.7.1 umap==0.4.2 numpy==1.18.3 scipy==1.4.1 pandas==1.0.3 scikit-learn==0.22.2.post1 statsmodels==0.11.1 python-igraph==0.8.2 louvain==0.6.2

### PR DESCRIPTION
**Pull request by mvdbeek**
Fixes
```
Traceback (most recent call last):
  File "/tmp/tmptq4o33we/job_working_directory/000/50/configs/tmpe21tizb1", line 29, in <module>
    scale='width')
  File "/usr/local/lib/python3.7/site-packages/scanpy/plotting/_tools/__init__.py", line 564, in rank_genes_groups_violin
    df[g] = X_col
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 3487, in __setitem__
    self._set_item(key, value)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 3563, in _set_item
    self._ensure_valid_index(value)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 3540, in _ensure_valid_index
    value = Series(value)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/series.py", line 314, in __init__
    data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 729, in sanitize_array
    raise Exception("Data must be 1-dimensional")
Exception: Data must be 1-dimensional
```

### CODE REVIEW

**Comment by ivirshup** [comment]
@fidelram, is this covered by #1529?

I supposed that we might want to merge this as a bugfix and have your PR go into 1.8?

**Comment by ivirshup** [comment]
Thanks for all these fixes @mvdbeek!

It looks like the issue here is less about `use_raw` and more about `X` being a two dimensional dense array. I think a more appropriate test would be to check that: if the plots are made using the same data, regardless of whether that data is dense, sparse, or in raw it should look the same. Basically, I'd expand the test introduced in #1548. It might be worth waiting to hear back from @fidelram before that though.

**Comment by pcm32** [comment]
Hi, anyway in which we could help on this? We need this fix for a training that we are conducting second half of April. Thanks!

**Comment by mvdbeek** [comment]
I think we can work without this particular fix, we probably only need to update the test data.

**Comment by mvdbeek** [comment]
Nope, I don't think we can work around this. If the fix is not right, could someone take the tests that are included here and fix them ?

**Comment by fidelram** [comment]
At some point we changed the return values of the anndata slicing and that is why I think the check for sparse was needed.

My recommendation is to replace this whole block

```python
        for g in _gene_names:
            if adata.raw is not None and use_raw:
                X_col = adata.raw[:, g].X
                if gene_symbols:
                    g = adata.raw.var[gene_symbols][g]
            else:
                X_col = adata[:, g].X
                if gene_symbols:
                    g = adata.var[gene_symbols][g]
            if issparse(X_col):
                X_col = X_col.toarray().flatten()
            X_col = X_col.toarray().flatten()
            new_gene_names.append(g)
            df[g] = X_col
```

by 
```python
   df = sc.get.obs_df(adata, _gene_names, use_raw=use_raw, gene_symbols=gene_symbols
  new_gene_names = df.columns
```

`sc.get.obs_df` is a well tested function and using it makes it easier for maintenance.

**Comment by giovp** [comment]
@mvdbeek does the solution from @fidelram solves the issue? if yes, would you be able to push updates to this PR?

**Comment by giovp** [comment]
Ok this should be good to go @ivirshup , I've incorporated the suggestion from @fidelram , thanks @mvdbeek for first attempt and tests!

**Review by ivirshup — COMMENTED** [review]
@giovp, do you know what the relationship between this and #1529 is? I wasn't sure if that was a more general fix.

Otherwise, looks good. Needs a release note (1.7.3) and then feel free to merge.

**Comment by giovp** [comment]
Hi @ivirshup ,

just checked #1529 , that's a more general additions to `rank_genes_groups_matrixplot` and `rank_genes_groups_dotplot`, but does not address this bug of `violinplot` which has to do with sparse `adata.X`. This also adds a test for that case. Thanks for pointing it out.
I'll add release note and merge it.

**Comment by ivirshup** [comment]
Ah, I was thinking more in the sense that `gene_symbols` is broken for most of the `rank_genes_groups` plots. That PR adds handling for `gene_symbols` in `_rank_genes_groups_plot`, but I see that's `rank_genes_group_violin` is not handled with the other plot types.

**Comment by giovp** [comment]
> Ah, I was thinking more in the sense that gene_symbols is broken for most of the rank_genes_groups plots. That PR adds handling for gene_symbols in _rank_genes_groups_plot, but I see that's rank_genes_group_violin is not handled with the other plot types.

right yes, can also merge it in #1529 instead of master if you think it's better.

**Comment by ivirshup** [comment]
No, might as well get it fixed now. I'm not sure if there are other reason's this plot is treated differently, and I'm not sure if Fidel was done with that PR.

**Comment by giovp** [comment]
thanks @mvdbeek , added release, will go on and merge this as soon as tests pass

**Pull request merged**
