### PR TITLE
Add some missing requirements

### PR DESCRIPTION
**Pull request by bebatut**
Hi,

I was testing the different functions and found out that some requirements were missing and so in the `requirements.txt`. I tried to add the one I could find on Pypi.

Bérénice

### CODE REVIEW

**Comment by falexwolf** [comment]
Sorry, all of these packages aren't necessary for Scanpy's core functionality, supposed to be treated as extensions and shouldn't be installed by default.

Hopefully we'll have a way of handling this that makes it more clear in the future.

**Comment by bgruening** [comment]
@falexwolf the problem is that there are functions that do now work without them and our down stream packages do not work ootb. Would it be possible to add a second file, e.g. `requirements-ect.txt` to keep track of this?

This file could also be used to create testing environments easily.

**Comment by flying-sheep** [comment]
here we are:

https://github.com/theislab/scanpy/blob/6c786e70cecc2581a8009f83e3c843c8e998946c/setup.py#L25-L29

Doesn’t look complete though. Would someone like to complete it?

**Comment by falexwolf** [comment]
Yes, we can simply add @bebatut's packages as an `ext` flag in the setup.

**Comment by falexwolf** [comment]
PR welcome! 🙂

**Pull request closed without merging**
