### PR TITLE
Added annotate_var_explained parameter to pl.pca

### PR DESCRIPTION
**Pull request by bfurtwa**
Passing annotate_var_explained to sc.pl.pca() adds the explained variance per component into the axis labels.
#1445

### CODE REVIEW

**Comment by giovp** [comment]
Thanks a lot for submitting a PR!!!
Will add as reviewer core dev @fidelram to see what he thinks. It's a bit an ad-hoc since it's an additional argument just for this function.

Meanwhile, for failing tests, can you reformat with black? That seems the reason why tests are failing.
```bash
pip install black #if you don't have it installed
black scanpy/plotting/_tools/scatterplots.py
```
or you can do the same from within whatever IDE you work with.

Thank you!

**Comment by fidelram** [comment]
Thanks for the PR. 

I am not a big fan of adding more and more parameters to generic functions like `embedding`. Rather, would be better if this code is handled in the `pca` function itself. 

In other words, could be possible to add the code to annotate the axis labels in the `pca` function and not in the `embedding` function?

**Comment by bfurtwa** [comment]
I could change the labels in the `fig` or `axs` objects in `pca `returned from `embedding`, but I think it would break the `savefig_or_show `feature as this saves the figure inside `embedding`, before returning to `pca`.

**Comment by fidelram** [comment]
Two ideas:  
 1.  pass to `embedding` `show=False, save=False` and then call `save_fig_or_show` within `pca` with the user values for `show` and `save`.
 2.  allow `embedding` to rename any axis using a parameter like `component_labels`. Thus, this feature is not specific to PCA but also available to any other embedding.

**Pull request merged**
