### PR TITLE
Add rtd-sphinx-search

### LINKED ISSUE #2763: Broken search results on the website
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [X] (optional) I have confirmed this bug exists on the master branch of scanpy.

### What happened?

When you print something in the search bar on the [documentation website](https://scanpy.readthedocs.io/en/stable/index.html), sometimes suggested links are broken. See the example for `sc.pl.umap` below.

Using google, I was able to find a correct page. Here is the correct and the broken link:
- Broken: https://scanpy.readthedocs.io/en/latest/generated/scanpy.pl.umap.html#scanpy-pl-umap
- Correct: https://scanpy.readthedocs.io/en/stable/generated/scanpy.pl.umap.html#scanpy-pl-umap

The difference is in latest/stable part. I tried searching for other functions as well, but did not notice any pattern. Here are some other links from search suggestion that are broken:
- https://scanpy.readthedocs.io/en/latest/generated/scanpy.external.tl.phenograph.html
- https://scanpy.readthedocs.io/en/latest/generated/scanpy.pl.rank_genes_groups_dotplot.html
- Same for other visualizations of rank_genes_group. `tl.rank_genes_groups` works, though

And a related issue. Why doesn't scanpy have a custom 404 page? 😄 

### Minimal code sample

Here's an example with looking for umap plot:
- Search suggests a page:
 
image

- First link (to the tool) is correct, but by clicking on the second one (for plotting) user gets 404:

image

### Error output

_No response_

### Versions

I was at the "stable" version on the website. Current scanpy version is 1.9.6

### PR DESCRIPTION
**Pull request by flying-sheep**
<!--
Thanks for opening a PR to scanpy!
Please be sure to follow the guidelines in our contribution guide (https://scanpy.readthedocs.io/en/latest/dev/index.html) to familiarize yourself with our workflow and speed up review.
-->

<!-- Please check (“- [x]”) and fill in the following boxes -->
- [x] Closes https://github.com/scverse/scanpy/issues/2763
- [x] Tests included or not required because: manually checked using rtd PR build
<!-- Only check the following box if you did not include release notes -->
- [ ] Release notes not necessary because:

Adds [readthedocs-sphinx-search](https://readthedocs-sphinx-search.readthedocs.io/en/latest/) support via the scanpydoc theme, which contains JS and CSS customizations to make the search extension integrate with the theme. See

- https://github.com/theislab/scanpydoc/pull/121
- https://github.com/theislab/scanpydoc/pull/125

### [rendered](https://icb-scanpy--2805.com.readthedocs.build/en/2805/)

An alternative that looks nicer would be https://github.com/readthedocs/addons, but it’s still in alpha

PS: I didn’t add the same hack as in scanpydoc that makes the search work in PR builds, so you’ll only see “No results found” in the above. Check out https://icb-scanpydoc.readthedocs-hosted.com/en/latest/?rtd_search=scanpydoc to see rendered search results. You can see that the API works for scanpy:

```console
$ http get https://icb-scanpy.readthedocs-hosted.com/_/api/v3/search/?q=project%3Aicb-scanpy%2Flatest+filter_cells
╭──────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ count    │ 2                                                                                                                                                                                                                                                                                  │
│ next     │                                                                                                                                                                                                                                                                                    │
│ previous │                                                                                                                                                                                                                                                                                    │
│          │ ╭───┬────────────┬────────────────╮                                                                                                                                                                                                                                                │
│ projects │ │ # │    slug    │    versions    │                                                                                                                                                                                                                                                │
│          │ ├───┼────────────┼────────────────┤                                                                                                                                                                                                                                                │
│          │ │ 0 │ icb-scanpy │ ╭───┬────────╮ │                                                                                                                                                                                                                                                │
│          │ │   │            │ │ # │  slug  │ │                                                                                                                                                                                                                                                │
│          │ │   │            │ ├───┼────────┤ │                                                                                                                                                                                                                                                │
│          │ │   │            │ │ 0 │ latest │ │                                                                                                                                                                                                                                                │
│          │ │   │            │ ╰───┴────────╯ │                                                                                                                                                                                                                                                │
│          │ ╰───┴────────────┴────────────────╯                                                                                                                                                                                                                                                │
│ query    │ filter_cells                                                                                                                                                                                                                                                                       │
│          │ ╭───┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────╮ │
│ results  │ │ # │                                                                                                                                blocks                                                                                                                                │ ... │ │
│          │ ├───┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────┤ │
│          │ │ 0 │ ╭───┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────╮ │ ... │ │
│          │ │   │ │ # │                                                                                                                        content                                                                                                                         │ ... │ │     │ │
│          │ │   │ ├───┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────┤ │     │ │
│          │ │   │ │ 0 │ figdir (scanpy._settings.ScanpyConfig property) file_format_data (scanpy._settings.ScanpyConfig property) file_format_figs (scanpy._settings.ScanpyConfig property) filter_cells() (in module scanpy.pp) filter_genes() (in module scanpy.pp)          │ ... │ │     │ │
│          │ │   │ │   │ filter_genes_dispersion() (in module scanpy.pl) (in module scanpy.pp) filter_rank_genes_groups() (in module scanpy.tl)                                                                                                                                 │     │ │     │ │
│          │ │   │ ╰───┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────╯ │     │ │
│          │ │ 1 │ ╭───┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────╮ │ ... │ │
│          │ │   │ │ # │                                                                                                                        content                                                                                                                         │ ... │ │     │ │
│          │ │   │ ├───┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────┤ │     │ │
│          │ │   │ │ 0 │ Normalize total counts per cell. Warning Deprecated since version 1.3.7: Use normalize_total() instead. The new function is equivalent to the present function, except that the new function doesn’t filter cells based on min_counts, use             │ ... │ │     │ │
│          │ │   │ │   │ filter_cells() if filtering is needed. some arguments were renamed copy is replaced by inplace Normalize each cell by total counts over all genes, so that every cell has the same total count after normalization. Similar functions are used, for    │     │ │     │ │
│          │ │   │ │   │ example, by Seurat [Satija15], Cell Ranger [Zheng17] or SPRING [Weinreb17]. Parameters: data AnnData | ndarray | spmatrixThe (annotated) data matrix of shape n_obs × n_vars. Rows correspond to cells and columns to genes. counts_per_cell_after     │     │ │     │ │
│          │ │   │ │   │ Optional[float] (default: None)If None, after normalization, each cell has a total count equal to the median of the counts_per_cell before normalization. counts_per_cell Optional[ndarray] (default: None)Precomputed counts per cell. key_n_counts   │     │ │     │ │
│          │ │   │ │   │ str (default: 'n_counts')Name of the field in adata.obs where the total counts per cell are stored. copy bool (default: False)If an AnnData is passed, determines whether a copy is returned. min_counts int (default: 1)Cells with counts less than   │     │ │     │ │
│          │ │   │ │   │ min_counts are filtered out during normalization. Return type: UnionType[AnnData, ndarray, spmatrix, None] Returns: Returns None if copy=False, else returns an updated AnnData object. Sets the following fields: adata.Xnumpy.ndarray |              │     │ │     │ │
│          │ │   │ │   │ scipy.sparse._csr.csr_matrix (dtype float)Normalized count data matrix. Examples >>> import scanpy as sc >>> adata = AnnData(np.array([[1, 0], [3, 0], [5, 6]], dtype=np.float32)) >>> print(adata.X.sum(axis=1)) [ 1. 3. 11.] >>>                     │     │ │     │ │
│          │ │   │ │   │ sc.pp.normalize_per_cell(adata) >>> print(adata.obs) n_counts 0 1.0 1 3.0 2 11.0 >>> print(adata.X.sum(axis=1)) [3. 3. 3.] >>> sc.pp.normalize_per_cell( ... adata, counts_per_cell_after=1, ... key_n_counts='n_counts2', ... ) >>> print(adata.obs)  │     │ │     │ │
│          │ │   │ │   │ n_counts n_counts2 0 1.0 3.0 1 3.0 3.0 2 11.0 3.0 >>> print(adata.X.sum(axis=1)) [1. 1. 1.]                                                                                                                                                            │     │ │     │ │
│          │ │   │ ╰───┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────╯ │     │ │
│          │ ╰───┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────╯ │
╰──────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

### CODE REVIEW

**Review by ivirshup — CHANGES_REQUESTED** [review]
I'm running into some bugs related to the theme's search:

First, this shortcut is shown though I think `/` is the shortcut used by sphinx.

image

If I hit `Cmd-K` I get:

image

If I `Esc` out of that I get:

image

---------

Is it possible to just not ship the javascript/ css that the pydata theme uses for search?

----

Code changes otherwise look good.

**Comment by flying-sheep** [comment]
> Is it possible to just not ship the javascript/ css that the pydata theme uses for search?

No, they have all their JS in [one file](https://github.com/pydata/pydata-sphinx-theme/blob/2057612a6f2fb5f044f0ea4a12912fd67f6c9cae/src/pydata_sphinx_theme/assets/scripts/pydata-sphinx-theme.js) which we don’t want to re-implement. But I’m pretty sure I know how to fix this issue.

**Comment by flying-sheep** [comment]
OK, done! https://github.com/theislab/scanpydoc/pull/128 is released and this PR is updated.

I’m not touching the `/` shortcut: meta/ctrl+k is advertised in a prominent spot and I don’t want to accidentally swallow a user trying to type `/` somewhere.

**Comment by ivirshup** [comment]
Found a couple more things. Mainly shortcut related:

## Shortcut overriding system shortcuts

Typically `Cmd-Delete` deletes a whole line of text for me. This doesn't happen in the search bar for the pydata sphinx theme. However it does work on the readthedocs site.

Can we prevent the theme from intercepting and overriding this hotkey?

## Shortcut opens but does not close search palette

`Cmd-K` will open, but not close the search palette. On the pydata sphinx demo site it both opens and closes the palette.

On readthedocs, `/` will only open the palette and `Esc` is needed to close it (AFAICT).

--------

For both of these, I think it would be nice to just be a bit more consistent with one of the options.

Are any improvements here reasonably easy to do? I recognize that it's making two libraries talk to each other, and at least one of them can't be totally turned off, so this might be difficult.


## "Hide search matches"  button appearing when it shouldn't (no action needed)

This is unrelated to the PR and seems to happen for all our PR builds. No action needed, just noting it

If I search for something, hit enter to go to the full results, then go back to the main page I get this little banner on top:

image

Note that this doesn't happen just for search results. It happens for any link I click, eg: table of contents. This doesn't happen on our live sites though.

**Review by ivirshup — COMMENTED** [review]
Found a couple more things. Mainly shortcut related:

## Shortcut overriding system shortcuts

Typically `Cmd-Delete` deletes a whole line of text for me. This doesn't happen in the search bar for the pydata sphinx theme. However it does work on the readthedocs site.

Can we prevent the theme from intercepting and overriding this hotkey?

## Shortcut opens but does not close search palette

`Cmd-K` will open, but not close the search palette. On the pydata sphinx demo site it both opens and closes the palette.

On readthedocs, `/` will only open the palette and `Esc` is needed to close it (AFAICT).

--------

For both of these, I think it would be nice to just be a bit more consistent with one of the options.

Are any improvements here reasonably easy to do? I recognize that it's making two libraries talk to each other, and at least one of them can't be totally turned off, so this might be difficult.


## "Hide search matches"  button appearing when it shouldn't (no action needed)

This is unrelated to the PR and seems to happen for all our PR builds. No action needed, just noting it

If I search for something, hit enter to go to the full results, then go back to the main page I get this little banner on top:

image

Note that this doesn't happen just for search results. It happens for any link I click, eg: table of contents. This doesn't happen on our live sites though.

**Comment by flying-sheep** [comment]
> Are any improvements here reasonably easy to do? I recognize that it's making two libraries talk to each other, and at least one of them can't be totally turned off, so this might be difficult.

yes, both things are quite easy, I think. Event listeners can be registered in a way that they don’t capture the event, and toggling the popup is a simple `if (isModalVisible()) removeSearchModal() else showSearchModal()`.

**Comment by flying-sheep** [comment]
All done! The “eats my <kbd>ctrl</kbd>/<kbd>⌘</kbd>+<kbd>⌫</kbd>” problem isn’t from my customizations, it’s https://github.com/pydata/pydata-sphinx-theme/issues/1645

**Review by ivirshup — APPROVED** [review]

**Pull request merged**
