### PR TITLE
Make diffusion maps compatible with new Neighbors class

### PR DESCRIPTION
**Pull request by gokceneraslan**
sc.tl.diffmap is not using new neighbors attributes.

### CODE REVIEW

**Comment by falexwolf** [comment]
Oh man, how did that happen? To myself: Is there really no separate call to diffmaps anywhere in the notebooks?... Thank you so much!

**Comment by gokceneraslan** [comment]
No problem. I think increasing the test coverage should be prioritised to make scanpy more robust.

**Comment by falexwolf** [comment]
Yes... you're of course right. For now, I added the call of diffmaps to a notebook... When graph abstraction is finished, I'll think about systematically adding a lot more tests...

**Comment by falexwolf** [comment]
PS: Your fix is also out in 1.0.1.

**Pull request merged**
