### PR TITLE
Add layer option to pca

### PR DESCRIPTION
**Pull request by Koncopd**
https://github.com/theislab/scanpy/issues/1301

### CODE REVIEW

**Comment by Koncopd** [comment]
@ivirshup 
Responding to [this](https://github.com/theislab/scanpy/issues/1301#issuecomment-654772068).

The problem with `{prefix}_pca` to `obsm` is that we have naming conventions for `basis='pca'` - this translates to `obsm['X_pca']` in some plotting fucntions.

**Comment by ivirshup** [comment]
Oh, no need to do this, I've already got this working a bit more generically (also supports `obsm`) with tests. Just wasn't sure about how to do the keys.

**Comment by Koncopd** [comment]
No problems, closing this then.

**Comment by Hrovatin** [comment]
So what is now the recommended way of calculating and plotting PCA on layers? Is it still the same as suggested in https://github.com/theislab/scanpy/issues/1301? With this I am still unable to use sc.pl.pca_variance_ratio.

**Comment by Ebony-Watson** [comment]
Any update on this? I can't figure out a way to run PCA on a specified layer & get the additional returns beyond the PCA plot.

**Pull request closed without merging**
