### PR TITLE
Make Scrublet batch-aware

### PR DESCRIPTION
**Pull request by pinin4fjords**
This PR makes adjustments for handling batch correctly while running Scrublet:

- Run scrublet separately on individual batches where applicable. Where this is the case, results stored in .uns are further keyed by batch (e.g. thershold selected etc), while the doublet scores are stored together in .obs.
- Scrublet plotting function needs to account for the changes in the object, and will plot the multiple batches together automatically.

scrublet_score_distributionfinal

### CODE REVIEW

**Comment by pinin4fjords** [comment]
I'm not sure what the CI issues are here, but they seem unrelated to the last commit

**Comment by pinin4fjords** [comment]
Any chance of this getting a look-in @ivirshup ?

**Review by ivirshup — COMMENTED** [review]
Hey, sorry about the late response!

Would you mind separating out the bug fix and feature addition? That was the bug fix can be released more quickly.

-------------

Question about the main idea here: what kind of batches are you expecting to handle here?

If they were from completley separate sequencing experiments, would you want to have variable expected doublet rates between batches?

If the batches are multiple samples that were barcoded and multiplexed, would you want to allow for the possibility of multiplets across batches?

--------

Could you also merge master into this? CI should be fixed now.

**Comment by pinin4fjords** [comment]
> Hey, sorry about the late response!

No worries!

> Would you mind separating out the bug fix and feature addition? That was the bug fix can be released more quickly.

OK, will do- see https://github.com/theislab/scanpy/pull/2023, https://github.com/theislab/scanpy/pull/2025

> Question about the main idea here: what kind of batches are you expecting to handle here?
> 
> If they were from completely separate sequencing experiments, would you want to have variable expected doublet rates between batches?
> 
> If the batches are multiple samples that were barcoded and multiplexed, would you want to allow for the possibility of multiplets across batches?

So, really, I just want to be able to follow best practice as per the [Scrublet docs](https://github.com/swolock/scrublet#best-practices), to be able to run Scrublet on cells from different samples separately, perhaps batches is the wrong term. Do you have a preferred alternative, or should I just clarify the help text?

> Could you also merge master into this? CI should be fixed now.

Done

**Comment by pinin4fjords** [comment]
@ivirshup I've merged the changes in master from those factored-out PRs, and added a couple of tests. Ready for review.

**Review by ivirshup — COMMENTED** [review]
Thanks for updating this, and sorry about the late review.

On the code, I think the plotting function could be cleaned up a bit. Maybe something like this could reduce repetition:

<details>
<summary> Different version of `scrublet_score_distribution ` </summary>

```python
def scrublet_score_distribution(
    adata,
    scale_hist_obs: str = 'log',
    scale_hist_sim: str = 'linear',
    figsize: Optional[Tuple[float, float]] = (8, 3),
    return_fig: bool = False,
    show: bool = True,
    save: Optional[Union[str, bool]] = None,
):
    """\
    Plot histogram of doublet scores for observed transcriptomes and simulated doublets.

    The histogram for simulated doublets is useful for determining the correct doublet
    score threshold.

    Scrublet must have been run previously with the input object.

    Parameters
    ----------
    adata
        An annData object resulting from func:`~scanpy.external.scrublet`.
    scale_hist_obs
        Set y axis scale transformation in matplotlib for the plot of observed
        transcriptomes (e.g. "linear", "log", "symlog", "logit")
    scale_hist_sim
        Set y axis scale transformation in matplotlib for the plot of simulated
        doublets (e.g. "linear", "log", "symlog", "logit")
    figsize
        width, height
    show
         Show the plot, do not return axis.
    save
        If `True` or a `str`, save the figure.
        A string is appended to the default filename.
        Infer the filetype if ending on {`'.pdf'`, `'.png'`, `'.svg'`}.

    Returns
    -------
    If `return_fig` is True, a :class:`~matplotlib.figure.Figure`.
    If `show==False` a list of :class:`~matplotlib.axes.Axes`.

    See also
    --------
    :func:`~scanpy.external.pp.scrublet`: Main way of running Scrublet, runs
        preprocessing, doublet simulation and calling.
    :func:`~scanpy.external.pp.scrublet_simulate_doublets`: Run Scrublet's doublet
        simulation separately for advanced usage.
    """

    def _plot_scores(
        ax: plt.Axes, scores: np.ndarray, scale: str, title: str, threshold=None
    ):
        ax.hist(
            scores,
            np.linspace(0, 1, 50),
            color='gray',
            linewidth=0,
            density=True,
        )
        ax.set_yscale(scale)
        yl = ax.get_ylim()
        ax.set_ylim(yl)

        if threshold is not None:
            ax.plot(threshold * np.ones(2), yl, c='black', linewidth=1)

        ax.set_title(title)
        ax.set_xlabel('Doublet score')
        ax.set_ylabel('Prob. density')

    if 'scrublet' not in adata.uns:
        raise ValueError(
            'Please run scrublet before trying to generate the scrublet plot.'
        )

    # If batched_by is populated, then we know Scrublet was run over multiple batches

    if 'batched_by' in adata.uns['scrublet']:
        batched_by = adata.uns['scrublet']['batched_by']
        batches = adata.obs[batched_by].astype("category", copy=False)
        n_batches = len(batches.cat.categories)
        figsize = (figsize[0], figsize[1] * n_batches)
    else:
        batches = pd.Series(
            np.broadcast_to(0, adata.n_obs), dtype="category", index=adata.obs_names
        )
        n_batches = 1

    fig, axs = plt.subplots(n_batches, 2, figsize=figsize)

    for idx, (batch_key, sub_obs) in enumerate(adata.obs.groupby(batches)):

        # We'll need multiple rows if Scrublet was run in multiple batches
        if 'batched_by' in adata.uns['scrublet']:

            threshold = adata.uns["scrublet"]['batches'][batch_key].get(
                "threshold", None
            )
            doublet_scores_sim = adata.uns['scrublet']['batches'][batch_key][
                'doublet_scores_sim'
            ]
            axis_lab_suffix = " (%s)" % batch_key
            obs_ax = axs[idx][0]
            sim_ax = axs[idx][1]

        else:
            threshold = adata.uns["scrublet"].get("threshold", None)
            doublet_scores_sim = adata.uns['scrublet']['doublet_scores_sim']
            axis_lab_suffix = ''
            obs_ax = axs[0]
            sim_ax = axs[1]

        # Make the plots
        _plot_scores(
            obs_ax,
            sub_obs["doublet_score"],
            scale=scale_hist_obs,
            title=f"Observed transcriptomes {axis_lab_suffix}",
            threshold=threshold,
        )
        _plot_scores(
            sim_ax,
            doublet_scores_sim,
            scale=scale_hist_sim,
            title=f"Simulated doublets {axis_lab_suffix}",
            threshold=threshold,
        )

    fig.tight_layout()

    _utils.savefig_or_show('scrublet_score_distribution', show=show, save=save)
    if return_fig:
        return fig
    elif not show:
        return axs

```

</details>

I was thinking it might be a little strange to have a function which takes into account batch where each batch is operated on separately. In this case it may make sense to just keep the datasets in separate AnnDatas when calling doublets. But it is fairly common to get "multiple samples" together in one file.

If you're up for swapping out the plotting function I think I'd be happy to merge.

**Comment by ivirshup** [comment]
Oh, and one more thing. It would be great if the test for the batched version could check it was equivalent to computing the doublets separately.

E.g.

<details>
<summary> modified `test_scrublet_batched` </summary>

```python
def test_scrublet_batched():
    """
    Test that Scrublet run works with batched data.

    Check that scrublet runs and detects some doublets.
    """
    pytest.importorskip("scrublet")

    adata = sc.datasets.pbmc3k()
    adata.obs['batch'] = 1350 * ['a'] + 1350 * ['b']
    split = [adata[adata.obs["batch"] == x].copy() for x in ("a", "b")]

    sce.pp.scrublet(adata, use_approx_neighbors=False, batch_key='batch')

    # replace assertions by conditions
    assert "predicted_doublet" in adata.obs.columns
    assert "doublet_score" in adata.obs.columns

    assert adata.obs["predicted_doublet"].any(), "Expect some doublets to be identified"
    assert (
        'batches' in adata.uns['scrublet'].keys()
    ), "Expect .uns to contain batch info"

    # Check that results are independent
    for s in split:
        sce.pp.scrublet(s, use_approx_neighbors=False)
    merged = sc.concat(split)

    pd.testing.assert_frame_equal(adata.obs[merged.obs.columns], merged.obs)
```

</details>

--------

For the docs, I think you might need to merge from master to get them to build. Sphinx has been acting up a lot recently.

**Comment by ivirshup** [comment]
Looks good, thanks for the PR!

**Comment by pinin4fjords** [comment]
Thanks @ivirshup , tried to comment yesterday but GitHub was unwell- good to see this finally merged.

**Comment by pinin4fjords** [comment]
(and fingers crossed for a release soon, I currently have a nasty patch in place for our pipelines)

**Pull request merged**
